### PR TITLE
Copter: Guided Angle: Initialize yaw to current yaw.

### LINKED ISSUE #26404: Unable to command velocity in GUIDED MODE
## Bug report

Unable to command velocity commands (in GUIDED mode)  through  SET_POSITION_TARGET_GLOBAL_INT/ SET_POSITION_TARGET_LOCAL_NED

I'm trying to command the bird's velocity in SITL through mavutil using the above messages. However these commands/messages don't seem to be sending, In comparision, I am able to send the SET_ATTITUDE_TARGET message and send attitude commands(in GUIDED Mode). Is there any way I can command velocity (for Copter) in GUIDED Mode, am I missing something? 

**Version**
 V4.6.0-dev 

**Platform**

[  ] Copter

**Airframe type**
quad

**Hardware type**
using SITL 

[**Logs**]
[velocity_control.log](https://github.com/ArduPilot/ardupilot/files/14494073/velocity_control.log)

adding my code as well 

`

    import time
    import math

    from pymavlink import mavutil
    import numpy as np

    def set_target_velocity(velocity_x, velocity_z):
   

   
    
        msg = master.mav.set_position_target_global_int_encode(
                0,       # time_boot_ms (not used)
                0, 0,    # target system, target component
                mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT, # frame
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_X_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_Y_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_Z_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_VY_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_FORCE_SET |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_IGNORE |
                mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE,
                0, # lat_int - X Position in WGS84 frame in 1e7 * meters
                0, # lon_int - Y Position in WGS84 frame in 1e7 * meters
                0, # alt - Altitude in meters in AMSL altitude(not WGS84 if absolute or relative)
                # altitude above terrain if GLOBAL_TERRAIN_ALT_INT
                velocity_x, # X velocity in NED frame in m/s
                0, # Y velocity in NED frame in m/s
                velocity_z, # Z velocity in NED frame in m/s
                0, 0, 0, # afx, afy, afz acceleration (not supported yet, ignored in GCS_Mavlink)
                0, 0)    # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink) 
    
    
    
        for x in np.arange(0.0, 100, 0.1):
        
      
           master.mav.send(msg)

           time.sleep(0.1)
        
       
        
        
    master = mavutil.mavlink_connection('127.0.0.1:14550')

    master.wait_heartbeat()

    master.set_mode('GUIDED')
    print("Mode changed --")
    time.sleep(1)

    print("commanding")

    set_target_velocity(velocity_x = 10, velocity_z = 2) `

### PR DESCRIPTION
**Pull request by lthall**
This fixes #26404.

I am simply initialising the attitude to the current heading so it does not rotate when it doesn't receive an initial attitude like normal guided attitude mode.

### CODE REVIEW

**Comment by lthall** [comment]
solves #26404

File: ArduCopter/mode_guided.cpp [hunk 1]
```diff
@@ -313,14 +313,11 @@ void ModeGuided::angle_control_start()
 
     // initialise targets
     guided_angle_state.update_time_ms = millis();
-    guided_angle_state.attitude_quat.initialise();
+    guided_angle_state.attitude_quat.from_euler(Vector3f(0.0, 0.0, attitude_control->get_att_target_euler_rad().z));
```
Comment (ShevaDavid) [inline ArduCopter/mode_guided.cpp:316]: I might be wrong about it's impact, but attitude quaternion is also initialized in the `angle_control_run` method where timeout check happens. Maybe it should be adjusted there as well

Comment (ShevaDavid) [reply ArduCopter/mode_guided.cpp:316]: Ok, I did the test I my assumption turned out to be valid. After initial switch to GUIDED_NOGPS the vehicle keeps it's current orientation, but after 3 seconds of inactivity automatically rotates north. 
Applying the change in both places does resolve the problem

Comment (lthall) [reply ArduCopter/mode_guided.cpp:316]: Nice catch!. I will add that to the pr. Thank you very much!!

And thanks for testing this.

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in 4.5.2-beta1
