### PR TITLE
AC_AttitudeControl:AC_PosControl: vibration failsafe fix

### LINKED ISSUE #17834: Copter: vibration failsafe broken in 4.1
Sadly the vibration failsafe has been broken somehow between Copter-4.0 and 4.1.

This can be reproduced in SITL by doing the following:

1. start SITL copter
2. param set EK3_IMU_MASK 1 (to enable only a single IMU)
3. loiter
4. arm throttle
5. rc 3 2000 (climb to 30m)
6. rc 3 1500
7. param set SIM_ACC1_BIAS_Z 2 (to set an accelerometer bias of 2m/s/s)

The good news is:

1. the vibration compensation will be triggered
2. EKF failsafe triggers and teh vehicle switches to LAND

The bad news is the vehicle keeps climbing

### PR DESCRIPTION
**Pull request by lthall**
This PR fixes #17834

### CODE REVIEW

File: libraries/AC_AttitudeControl/AC_PosControl.cpp [hunk 1]
```diff
@@ -1003,8 +1003,8 @@ void AC_PosControl::get_stopping_point_xy_cm(Vector3f &stopping_point) const
 
     // add velocity error to current velocity
```
Comment (amilcarlucas) [inline libraries/AC_AttitudeControl/AC_PosControl.cpp:1004]: Comment must be updated

**Review by amilcarlucas — CHANGES_REQUESTED** [review]

File: libraries/AC_AttitudeControl/AC_PosControl.cpp (hunk 1 above)
Comment (lthall) [reply libraries/AC_AttitudeControl/AC_PosControl.cpp]: Thanks, done.

**Review by rmackay9 — APPROVED** [review]
I've tested in SITL and this fixes the vibration failsafe, thanks!
before-vs-after
