### PR TITLE
Fail to arm if in RC_Calibration

### LINKED ISSUE #8735: RC Cal Safety/Usability to prevent arming
Would be awesome if ArduPilot supported MAV_CMD_PREFLIGHT_CALIBRATION.param4=1/0 to start stop radio calibration. Mavlink spec is not super specific by in QGC this causes the motors to not arm when you are doing RC cal. This way you don't have to take props off during RC cal.

### PR DESCRIPTION
**Pull request by IamPete1**
Fixes #8735

Although as far as I can tell QGC no longer sets that bit. I think it would be a nice enhancement to all the GCSs tho.

I'm not sure on the exact way to use the pram. 

https://mavlink.io/en/messages/common.html#MAV_CMD_PREFLIGHT_CALIBRATION

Says: 
     1: radio RC calibration, 2: RC trim calibration

Currently I have 1 = running 0 = stop. But that means we cant ack the stop. Maybe it should be a continues set and timeout. Or a toggle. 

Since QGC seems not to send it anymore we have no base line to compare to....

### CODE REVIEW

**Comment by IamPete1** [comment]
Looks like QGC should be sending it, https://github.com/mavlink/qgroundcontrol/blob/27533e57a862288a22f6880f5591aa3c1c057cb2/src/Vehicle/Vehicle.cc#L3221

**Comment by IamPete1** [comment]
Plane and rover are already using this param, but both are using a value of 1 for copy trim where as the spec says that should be 2

https://github.com/ArduPilot/ardupilot/blob/8462ce4e2e32edcd6beaed28bdc6d892cad02059/Rover/GCS_Mavlink.cpp#L575

https://github.com/ArduPilot/ardupilot/blob/8462ce4e2e32edcd6beaed28bdc6d892cad02059/ArduPlane/GCS_Mavlink.cpp#L626

File: libraries/RC_Channel/RC_Channel.h [hunk 1]
```diff
@@ -572,6 +576,9 @@ class RC_Channels {
 
     // Allow override by default at start
     bool _gcs_overrides_enabled = true;
+
+    // true if GCS is performing a RC calibration
+    bool is_calibrating;
```
Comment (rmackay9) [inline libraries/RC_Channel/RC_Channel.h:581]: can we clarify this boolean's name?  maybe gcs_in_RC_calibration or something like that.

File: ArduCopter/AP_Arming.cpp [hunk 2]
```diff
@@ -746,7 +746,7 @@ bool AP_Arming_Copter::mandatory_checks(bool display_failure)
         result = false;
     }
 
-    return result;
+    return result & AP_Arming::mandatory_checks(display_failure);
```
Comment (tridge) [inline ArduCopter/AP_Arming.cpp:749]: && for boolean and

File: Blimp/AP_Arming.cpp [hunk 3]
```diff
@@ -303,7 +303,7 @@ bool AP_Arming_Blimp::mandatory_checks(bool display_failure)
         result = false;
     }
 
-    return result;
+    return result & AP_Arming::mandatory_checks(display_failure);
```
Comment (tridge) [inline Blimp/AP_Arming.cpp:306]: && for boolean

**Review by tridge — CHANGES_REQUESTED** [review]

File: ArduPlane/GCS_Mavlink.cpp [hunk 4]
```diff
@@ -619,7 +619,7 @@ MAV_RESULT GCS_MAVLINK_Plane::handle_command_preflight_calibration(const mavlink
 
 MAV_RESULT GCS_MAVLINK_Plane::_handle_command_preflight_calibration(const mavlink_command_long_t &packet)
 {
-    if (is_equal(packet.param4,1.0f)) {
+    if (is_equal(packet.param4,2.0f)) {
```
Comment (tridge) [inline ArduPlane/GCS_Mavlink.cpp:622]: better to remove trim_radio()

**Review by tridge — CHANGES_REQUESTED** [review]

**Review by tridge — APPROVED** [review]
