### PR TITLE
Copter: check if only one of MOT_PWM_MIN or MOT_PWM_MAX is set

### LINKED ISSUE #13242: Copter: add check if only one of MOT_PWM_MIN or MOT_PWM_MAX is set
This issue is raised in response to [this report on the forums](https://discuss.ardupilot.org/t/copter-4-0-did-great-thou-scary-with-hexa-failed-motor/50808/9) which involved a user setting the MOT_PWM_MIN parameter (presumably to ensure the output to the motors was never below this value) but failed to set the MOT_PWM_MAX value.

We should add a pre-arm check to ensure that both these valures are either zero or non-zero.  I.e. a situation where only one of them is non-zero should trigger a pre-arm failure.

### PR DESCRIPTION
**Pull request by ashvath100**
fixes #13242 

Pre-arm check to ensure that both MOT_PWM_MIN and MOT_PWM_MAX values are either zero or non-zero. When only one of them is non-zerol trigger a pre-arm failure.
Screenshot from 2020-01-22 00-59-51
Screenshot from 2020-01-22 01-00-29

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
Nice quick fix.  My only suggestion is to use the `IS_ZERO()` math function instead of == 0.  So for example `copter.motors->get_mot_pwm_min() == 0` would instead be `IS_ZERO(copter.motors->get_mot_pwm_min()`. Put a ! in front for the not zero check.

Maybe add a check for `IS_NEGATIVE()` on each as well to catch if someone entered a negative value that would be obviously invalid?

**Comment by ashvath100** [comment]
> Nice quick fix. My only suggestion is to use the `IS_ZERO()` math function instead of == 0. So for example `copter.motors->get_mot_pwm_min() == 0` would instead be `IS_ZERO(copter.motors->get_mot_pwm_min()`. Put a ! in front for the not zero check.
> 
> Maybe add a check for `IS_NEGATIVE()` on each as well to catch if someone entered a negative value that would be obviously invalid?

@Pedals2Paddles not sure if anyone would force add a negative pwm value , added a check anyhow

**Comment by Pedals2Paddles** [comment]
Never underestimate user error :).  Changes look perfect.

**Comment by peterbarker** [comment]
Looks fine to me.

What effects can a user expect in the circumstances that these would fail?

Also, is it valid for min to be greater than max?  No check for that yet :-)

**Comment by ashvath100** [comment]
@peterbarker I have added a check for min greater than max pwm

**Comment by Pedals2Paddles** [comment]
@rmackay9 this looks like it's good to go.

File: libraries/AP_Motors/AP_MotorsMulticopter.h [hunk 1]
```diff
@@ -84,6 +84,10 @@ class AP_MotorsMulticopter : public AP_Motors {
     int16_t             get_pwm_output_min() const;
     int16_t             get_pwm_output_max() const;
     
+    //get MOT_PWM_MIN or MOT_PWM_MAX value 
+    float               get_mot_pwm_min() const;
```
Comment (rmackay9) [inline libraries/AP_Motors/AP_MotorsMulticopter.h]: I think these parameters are actually int16..

**Comment by rmackay9** [comment]
@ashvath100, sorry to give you the run around on this but I'd like it if you could replace the accessors with a function that return a boolean that checks the validity of the paarmeter values.

So remove the get_mot_pwm_min() and get_mot_pwm_max() functions and instead have a function called something like check_mot_pwm_params() that returns true if they are all ok or false if something is wrong.   Then back in the AP_Arming_Copter() class call this new function and print "Check xxxx" - i.e. no need to specifically tell them that MIN>MAX or whatever.. just alert them that something is wrong is good enough.

... or another approach is to move the parameter_check() method up from the AP_MotorsHeli class into AP_Motors_Class.h and then implement the above stuff in a new AP_MotorsMulticopter::parameter_check() method.

Again, sorry for the varying advice, it's just that I suspect quadplane will want this check eventually as well and I worry that a developer in the future will get confused between these new accessors and the very similarly named get_pwm_output_min() and get_pwm_output_max().

**Comment by ashvath100** [comment]
> @ashvath100, sorry to give you the run around on this but I'd like it if you could replace the accessors with a function that return a boolean that checks the validity of the paarmeter values.
> 
> So remove the get_mot_pwm_min() and get_mot_pwm_max() functions and instead have a function called something like check_mot_pwm_params() that returns true if they are all ok or false if something is wrong. Then back in the AP_Arming_Copter() class call this new function and print "Check xxxx" - i.e. no need to specifically tell them that MIN>MAX or whatever.. just alert them that something is wrong is good enough.
> 
> ... or another approach is to move the parameter_check() method up from the AP_MotorsHeli class into AP_Motors_Class.h and then implement the above stuff in a new AP_MotorsMulticopter::parameter_check() method.
> 
> Again, sorry for the varying advice, it's just that I suspect quadplane will want this check eventually as well and I worry that a developer in the future will get confused between these new accessors and the very similarly named get_pwm_output_min() and get_pwm_output_max().

@rmackay9  the changes have been made

**Comment by rmackay9** [comment]
Great, thanks!

**Comment by rmackay9** [comment]
This is included in Copter-4.0.4-rc1
