### PR TITLE
SCurve: fix calculate_path bugs and add comprehensive tests

### LINKED ISSUE #32724: Copter/Rover: SCurve calculation formula
the calculation formula for  Sucrve about At
`void SCurve::calculate_path(float Sm, float Jm, float V0, float Am, float Vm, float L,float &Jm_out, float &tj_out,  float &t2_out, float &t4_out, float &t6_out)
{
  ...
    float At = MIN(MIN(Am, (Vm - V0) / (2.0f * tj) ), (L + 4.0f * V0 * tj) / (4.0f * sq(tj)) );
   ....
}
`
 should be 
float At = MIN(MIN(Am, (Vm - V0) / (2.0f * tj) ), (L - 4.0f * V0 * tj) / (4.0f * sq(tj)) );

### PR DESCRIPTION
**Pull request by lthall**
### Summary

Fix three bugs in SCurve::calculate_path and set_speed_max, add tests
that cover all code paths, and clean up float literal consistency.

Fixes #32724

Bug fixes:
- Fix sign error in path length acceleration constraint: (L + 4*V0*tj)
  should be (L - 4*V0*tj). The old formula inflated the allowed
  acceleration when V0 > 0, producing invalid motion profiles.
- Add early return when At <= 0. After the sign fix, At can go negative
  when the path is too short for the initial velocity.
- Fix integer division in set_speed_max: powf(x, 1/3) evaluated the
  exponent as 0, making powf always return 1.0 instead of the cube
  root. This disabled the velocity-based jerk time limit.
- Guard against divide-by-zero where dP is divided by
  segment[SEG_CONST].end_vel in four places.

Tests:
- 32 test cases covering all 8 code paths in calculate_path with 4
  inputs per path near transitions and midpoints.
- Constraint validation replicating the add_segments path structure to
  verify total distance, final velocity, final acceleration, and that
  velocity, acceleration, and jerk limits are not exceeded.

Cleanup:
- Replace double literals with float literals throughout to avoid
  implicit double-to-float conversions.
- Fix misleading comment, whitespace, and operator spacing.

```
Board,antennatracker,blimp,bootloader,copter,heli,plane,rover,sub
CubeOrange,*,*,*,128,128,136,136,128
```

### Classification & Testing (check all that apply and add your own)

- [x] Checked by a human programmer
- [ ] Non-functional change
- [ ] No-binary change
- [x] Infrastructure change (e.g. unit tests, helper scripts)
- [x] Automated test(s) verify changes (e.g. unit test, autotest)
- [ ] Tested manually, description below (e.g. SITL)
- [ ] Tested on hardware
- [ ] Logs attached
- [ ] Logs available on request

### CODE REVIEW

**Comment by amilcarlucas** [comment]
```
Binary Name      Text [B]        Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  --------------  -----------  -------------  ----------------------------  -------------------------
blimp            0 (0.0000%)     0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      780972
arducopter       128 (+0.0081%)  0 (0.0000%)  0 (0.0000%)    128 (+0.0080%)                                   374116
ardusub          124 (+0.0087%)  0 (0.0000%)  -4 (-0.0015%)  124 (+0.0086%)                                   530428
arducopter-heli  128 (+0.0081%)  0 (0.0000%)  0 (0.0000%)    128 (+0.0081%)                                   378508
arduplane        124 (+0.0078%)  0 (0.0000%)  -4 (-0.0016%)  124 (+0.0078%)                                   378184
ardurover        124 (+0.0086%)  0 (0.0000%)  4 (+0.0015%)   124 (+0.0085%)                                   512868
antennatracker   0 (0.0000%)     0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      800056
```

**Review by IamPete1 — APPROVED** [review]

**Comment by tpwrules** [comment]
Is this observable in flight?

**Comment by rmackay9** [comment]
Hi @tpwrules, my understanding from a quick chat with Leonard is that it is observable as an overshoot as the vehicle transitions from one waypoint to the next.

**Comment by lthall** [comment]
> Is this observable in flight?

I have tired to excite this but it is really difficult. I believe I have seen it once but then could not replicate it. I have spent some time trying but have not been succsessful.

File: libraries/AP_Math/SCurve.cpp [hunk 1]
```diff
@@ -294,7 +294,7 @@ void SCurve::set_speed_max(float speed_xy, float speed_up, float speed_down)
 
         // add to constant velocity segment to end at the correct position
         const float dP = MAX(0.0f, Pend - segment[SEG_DECEL_END].end_pos);
-        const float t15 = dP / segment[SEG_CONST].end_vel;
+        const float t15 = is_positive(segment[SEG_CONST].end_vel) ? dP / segment[SEG_CONST].end_vel : 0.0f;
```
Comment (andyp1per) [inline libraries/AP_Math/SCurve.cpp:297]: It's 124 bytes for doing the same check multiple times. You could probably avoid the impact of this by using a function

**Review by rmackay9 — APPROVED** [review]

File: libraries/AP_Math/SCurve.cpp (hunk 1 above)
Comment (lthall) [reply libraries/AP_Math/SCurve.cpp:297]: Good suggestion. Addressed in a follow up PR:

#32787

**Comment by Georacer** [comment]
This has been included in 4.7.0-beta4. Thanks!
