### PR TITLE
Fix dshot cancel race

### LINKED ISSUE #29370: AP-4.6.0: TradHeli internal errors 0X4000000 and 0X4000020
This issue is to capture the internal errors reported by @Ferruccio1984 during AP-4.6.0-beta3/4 testing ([discussion here](https://discuss.ardupilot.org/t/copter-4-6-0-beta4-released-for-beta-testing/130471/23))

### PR DESCRIPTION
**Pull request by andyp1per**
Alternative to https://github.com/ArduPilot/ardupilot/pull/29379 fixes #29370

This ensures dshot_waiter is only manipulated inside a system lock. Tested on a Pavo20Pro

### CODE REVIEW

File: libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp [hunk 1]
```diff
@@ -496,6 +496,11 @@ __RAMFUNC__ void RCOutput::bdshot_finish_dshot_gcr_transaction(virtual_timer_t*
 #ifdef HAL_GPIO_LINE_GPIO56
     TOGGLE_PIN_DEBUG(56);
 #endif
+    if (group->dshot_waiter == nullptr) {   // transaction was cancelled, leave everything alone
```
Comment (tridge) [inline libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp:499]: i think this change won't work, when the bug happens 'this' is nullptr, so we are checking an incorrect memory location

**Review by tridge — CHANGES_REQUESTED** [review]

File: libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp (hunk 1 above)
Comment (andyp1per) [reply libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp:499]: No, I don't think so. The "this" is a pointer set in the timer, it cannot be null unless the timer is reset in which case the callback is not called. The nullptr is not "this" but this->dshot_waiter which *was* so to nullptr outside of a lock hence the bug.

**Comment by andyp1per** [comment]
This was the crash:
```
#0  0x0813b21a in chEvtSignalI (tp=0x0, events=<optimized out>) at ../../modules/ChibiOS/os/rt/src/chevents.c:300
#1  0x081280e0 in ChibiOS::RCOutput::bdshot_finish_dshot_gcr_transaction (vt=<optimized out>, 
    p=0x24017548 <ChibiOS::RCOutput::pwm_group_list+1392>) at ../../libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp:544
#2  0x0813bd38 in chVTDoTickI () at ../../modules/ChibiOS/os/rt/src/chvt.c:537
#3  0x0813b86c in chSysTimerHandlerI () at ../../modules/ChibiOS/os/rt/src/chsys.c:403
#4  0x0813dafc in osalOsTimerHandlerI () at ../../modules/ChibiOS/os/hal/osal/rt-nil/osal.h:669
#5  st_lld_serve_interrupt () at ../../modules/ChibiOS/os/hal/ports/STM32/LLD/SYSTICKv1/hal_st_lld.c:615
#6  0x0813e032 in Vector108 () at ../../modules/ChibiOS/os/hal/ports/STM32/LLD/TIMv1/stm32_tim5.inc:129
#7  <signal handler called>
#8  0x08012500 in Copter::read_inertia (this=0x240033d8 <copter>) at ../../ArduCopter/inertia.cpp:7
#9  0x080798e8 in Functor<void>::operator() (this=0x8147e94 <Copter::scheduler_tasks+120>) at ../../libraries/AP_HAL/utility/functor.h:52
#10 AP_Scheduler::run (this=this@entry=0x24003608 <copter+560>, time_available=2104) at ../../libraries/AP_Scheduler/AP_Scheduler.cpp:264
#11 0x08079d3e in AP_Scheduler::loop (this=this@entry=0x24003608 <copter+560>) at ../../libraries/AP_Scheduler/AP_Scheduler.cpp:393
#12 0x0807b7f6 in AP_Vehicle::loop (this=0x240033d8 <copter>) at ../../libraries/AP_Vehicle/AP_Vehicle.cpp:544
#13 0x080e09b4 in main_loop () at ../../libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp:301
#14 HAL_ChibiOS::run (this=<optimized out>, argc=<optimized out>, argv=<optimized out>, callbacks=<optimized out>)
    at ../../libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp:354
#15 0x0800c3dc in main (argc=<optimized out>, argv=<optimized out>) at ../../ArduCopter/Copter.cpp:892
```
It's the signal on group->dshot_waiter that is the problem, not the de-reference of group

File: libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp (hunk 1 above)
Comment (andyp1per) [reply libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp:499]: Incidentally I don't believe this can ever be triggered because we now cancel the timer inside a lock together with setting the value to nullptr

Comment (tridge) [reply libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp:499]: you're right, sorry!

**Comment by tridge** [comment]
it would be good to run with --enable-asserts, and the MPU protection enabled with @Ferruccio1984 setup

**Comment by rmackay9** [comment]
This is related to the "TradHeli internal errors 0X4000000 and 0X4000020" issue on the 4.6 issues list https://github.com/ArduPilot/ardupilot/issues/28612

**Comment by tridge** [comment]
@andyp1per not building?

**Comment by andyp1per** [comment]
Briefly tested on my fast rate quad without issue

**Comment by tridge** [comment]
@andyp1per @Ferruccio1984 was this tested on the problem setup with asserts enabled?

**Comment by andyp1per** [comment]
@Ferruccio1984 's issue turned out to be flash ECC corruption which I was kind of expecting. Fully wiping the flash and re-flashing fixed the issue.

@tridge when I looked at the assertions the crash was actually happening inside the crashdump code - so the firmware was crashing trying to write a crashdump to flash. I am not sure what we can do about this.

**Comment by rmackay9** [comment]
this is included in 4.6.0-beta5
