### PR TITLE
AP_Param: fixed lockup in scripting due to save queue

### LINKED ISSUE #15997: Scripting: lockup with param save
If a lua script tries to write lots of mission items then we can get a complete lockup in SITL, and a block on the IO thread in a real flight controller
The problem is this:
https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Param/AP_Param.cpp#L1177
combined with the mission API in lua taking the scheduler semaphore:
https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Scripting/generator/description/bindings.desc#L249
the param save queue can never empty as the main thread is blocked by the scheduler semaphore. So if we fill that queue then the fc will lock waiting on IO thread

example:
```
-- auto-create mission
function create_mission()
   if mission:num_commands() == 0 then
      return
   end
   gcs:send_text(0, string.format("creating mission"))
   local wp1 = mission:get_item(0)
   mission:clear()
   for i = 1, 300 do
      mission:set_item(mission:num_commands(), wp1)
   end
end

function update()
   create_mission()
   return update, 2000
end

return update()
```

### PR DESCRIPTION
**Pull request by tridge**
this is a quick fix for a lockup in scripting due to the mission API
holding the scheduler semaphore when it is updating the mission count
parameter. 
Note that this bug is much worse on SITL as the IO thread is in the same thread as main thread. On a real board the impact depends on progress on the IO thread

The problem with this fix is it means the MIS_TOTAL may not be saved, so on reboot it could be wrong

Fixes #15997

some alternative approaches:
 - lose the scheduler semaphore in the save of MIS_TOTAL
 - add a is_owner() API to semaphores, and don't wait if we hold scheduler semaphore

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
MdB should look at this...

File: libraries/AP_Param/AP_Param.cpp [hunk 1]
```diff
@@ -1160,12 +1160,21 @@ void AP_Param::save_sync(bool force_save)
 */
 void AP_Param::save(bool force_save)
 {
-    struct param_save p;
+    struct param_save p, p2;
     p.param = this;
     p.force_save = force_save;
+    if (save_queue.peek(p2) &&
```
Comment (WickedShell) [inline libraries/AP_Param/AP_Param.cpp:1166]: I think it's fine, but it's worth noting that this depends upon grabbing a mutex from the save thread here to do this check. I think it will be fine, but I haven't fully followed the lock on the scheduler semaphore.

**Review by WickedShell — APPROVED** [review]

**Comment by WickedShell** [comment]
> - lose the scheduler semaphore in the save of MIS_TOTAL

This would be a bad solution as there are a lot of race conditions that suddenly arise when manipulating the mission. There isn't a simple set of locks we can put on this, particularly with the interactions of callbacks and similar.

File: libraries/AP_Param/AP_Param.cpp (hunk 1 above)
Comment (tridge) [reply libraries/AP_Param/AP_Param.cpp:1166]: yes, I think it is ok, as we are grabbing/releasing in the right order
