### PR TITLE
GCS_MAVLink: fix buffer overread on invalid SERIAL_CONTROL write

### LINKED ISSUE #32524: [BUG] Uninitialized Byte Propagation in ArduPilot's Live MAVLink SERIAL_CONTROL Forwarding Path
### Issue details

Latest-source `ArduPilot/ardupilot` still appears to propagate uninitialized bytes through the live MAVLink `SERIAL_CONTROL` forwarding path.

I rebuilt current upstream `ArduPlane` SITL from a fresh latest-source checkout, launched it through the normal `sim_vehicle.py` runtime, and sent crafted MAVLink `SERIAL_CONTROL` packets over the real transport path. The relevant path is:

- `MAVLINK_MSG_ID_SERIAL_CONTROL` dispatch in `GCS_Common.cpp`
- `GCS_MAVLINK::handle_serial_control()` in `GCS_serial_control.cpp`
- `SERIAL_CONTROL` message schema in `modules/mavlink/message_definitions/v1.0/common.xml`

The key code path forwards `packet.count` together with the fixed-width `packet.data[70]` buffer without re-validating that all referenced bytes are valid initialized payload bytes:

```cpp
if (packet.count != 0) {
    if ((packet.flags & SERIAL_CONTROL_FLAG_BLOCKING) == 0) {
        stream->write(packet.data, packet.count);
    } else {
        const uint8_t *data = &packet.data[0];
        uint8_t count = packet.count;
```
Using device=100 so the traffic takes the real SERIAL0 branch, valgrind on the running SITL binary reported repeated findings such as:

- Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
- uninitialized values originating from GCS_MAVLINK::raw_packetReceived(...)

This suggests that malformed SERIAL_CONTROL traffic can still cause uninitialized bytes to reach the outbound serial send buffer in the latest source.

**Version**
- ArduPilot git commit: bef33f44fc28b95281c858e55b783d1844980169
- Validation target: latest-source ArduPlane SITL build

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[✅] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
SITL fixed-wing / Plane default model

**Hardware type**
SITL (software-in-the-loop), no physical autopilot hardware

**Logs**
This is processed with full-path PoC.
```
==3486== ./.valgrindrc was not read as it is either not a regular file,
==3486==     or is world writeable, or is not owned by the current user.
==3486== Memcheck, a memory error detector
==3486== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==3486== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==3486== Command: /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin --model plane --speedup 1 --slave 0 --defaults Tools/autotest/models/plane.parm --sim-address=127.0.0.1 -I0 --home 37.619373,-122.376637,5.3,118.0 --serial0 udpclient:127.0.0.1:5760
==3486== 
Setting SIM_SPEEDUP=1.000000
Home: 37.619373 -122.376637 alt=5.300000m hdg=118.000000
Starting sketch 'ArduPlane'
Starting SITL input
Using Irlock at port : 9005
UDP connection 127.0.0.1:5760
Loaded defaults from Tools/autotest/models/plane.parm
bind port 5762 for SERIAL1
SERIAL1 on TCP port 5762
bind port 5763 for SERIAL2
SERIAL2 on TCP port 5763
Smoothing reset at 0.001
validate_structures:538: Validating structures
Waiting for internal clock bits to be set (current=0x00)
Loaded defaults from Tools/autotest/models/plane.parm
==3486== Conditional jump or move depends on uninitialised value(s)
==3486==    at 0x3F34C1: mavlink_packetise(ByteBuffer&, unsigned short) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x35DE51: HALSITL::UARTDriver::_timer_tick() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x357931: HALSITL::Scheduler::_run_io_procs() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354E24: HALSITL::SITL_State::_fdm_input_step() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354EBA: HALSITL::SITL_State::wait_clock(unsigned long) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x35768C: HALSITL::Scheduler::delay_microseconds(unsigned short) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x1EC959: AP_InertialSensor::wait_for_sample() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25B96C: AP_Scheduler::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25EC88: AP_Vehicle::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x352F10: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x171C83: main (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==  Uninitialised value was created by a stack allocation
==3486==    at 0x277871: GCS_MAVLINK::raw_packetReceived(unsigned char, __mavlink_status const&, __mavlink_message const&) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486== 
==3486== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==3486==    at 0x4D1CF2A: __libc_send (send.c:28)
==3486==    by 0x4D1CF2A: send (send.c:23)
==3486==    by 0x35DEC9: HALSITL::UARTDriver::_timer_tick() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x357931: HALSITL::Scheduler::_run_io_procs() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354E24: HALSITL::SITL_State::_fdm_input_step() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354EBA: HALSITL::SITL_State::wait_clock(unsigned long) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x35768C: HALSITL::Scheduler::delay_microseconds(unsigned short) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x1EC959: AP_InertialSensor::wait_for_sample() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25B96C: AP_Scheduler::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25EC88: AP_Vehicle::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x352F10: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x171C83: main (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==  Address 0x1fff0005e6 is on thread 1's stack
==3486==  in frame #1, created by HALSITL::UARTDriver::_timer_tick() (???:)
==3486==  Uninitialised value was created by a stack allocation
==3486==    at 0x277871: GCS_MAVLINK::raw_packetReceived(unsigned char, __mavlink_status const&, __mavlink_message const&) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486== 
==3486== Conditional jump or move depends on uninitialised value(s)
==3486==    at 0x3F34C1: mavlink_packetise(ByteBuffer&, unsigned short) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x35DE51: HALSITL::UARTDriver::_timer_tick() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x357931: HALSITL::Scheduler::_run_io_procs() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x352F15: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x171C83: main (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==  Uninitialised value was created by a stack allocation
==3486==    at 0x277871: GCS_MAVLINK::raw_packetReceived(unsigned char, __mavlink_status const&, __mavlink_message const&) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486== 
==3486== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==3486==    at 0x4D1CF2A: __libc_send (send.c:28)
==3486==    by 0x4D1CF2A: send (send.c:23)
==3486==    by 0x35DEC9: HALSITL::UARTDriver::_timer_tick() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x357931: HALSITL::Scheduler::_run_io_procs() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x352F15: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x171C83: main (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==  Address 0x1fff000732 is on thread 1's stack
==3486==  in frame #1, created by HALSITL::UARTDriver::_timer_tick() (???:)
==3486==  Uninitialised value was created by a stack allocation
==3486==    at 0x277871: GCS_MAVLINK::raw_packetReceived(unsigned char, __mavlink_status const&, __mavlink_message const&) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486== 
==3486== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==3486==    at 0x4D1CF2A: __libc_send (send.c:28)
==3486==    by 0x4D1CF2A: send (send.c:23)
==3486==    by 0x35DEC9: HALSITL::UARTDriver::_timer_tick() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x357931: HALSITL::Scheduler::_run_io_procs() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354D74: HALSITL::SITL_State::_fdm_input_local() [clone .part.0] (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354DC6: HALSITL::SITL_State::_fdm_input_step() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x354EBA: HALSITL::SITL_State::wait_clock(unsigned long) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x35768C: HALSITL::Scheduler::delay_microseconds(unsigned short) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25BA2A: AP_Scheduler::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x25EC88: AP_Vehicle::loop() (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x352F10: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==    by 0x171C83: main (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486==  Address 0x1fff00059c is on thread 1's stack
==3486==  in frame #1, created by HALSITL::UARTDriver::_timer_tick() (???:)
==3486==  Uninitialised value was created by a stack allocation
==3486==    at 0x277871: GCS_MAVLINK::raw_packetReceived(unsigned char, __mavlink_status const&, __mavlink_message const&) (in /mnt/ssd1/chxrd/trarc/relocated_from_repo/analysis_output/poc_validation/logs/ardupilot_arduplane_sitl_latest_fullpath_rerun3.bin)
==3486== 
```

### PR DESCRIPTION
**Pull request by tpwrules**
## Summary

Fix sending junk if an incorrectly large count is sent in the SERIAL_CONTROL message.

Closes #32524 .

## Testing (more checks increases chance of being merged)

- [X] Checked by a human programmer
- [ ] Tested in SITL
- [ ] Tested on hardware
- [ ] Logs attached
- [ ] Logs available on request
- [ ] Autotest included

## Description

Setting a count in the packet bigger than the data buffer size could result in reading past the decoded packet and sending random junk off the stack. Fix by capping the size to send at the buffer size, as there is no ability for returning failure at this time. The recieve path is already protected similarly.

### CODE REVIEW

File: libraries/GCS_MAVLink/GCS_serial_control.cpp [hunk 1]
```diff
@@ -116,6 +116,10 @@ void GCS_MAVLINK::handle_serial_control(const mavlink_message_t &msg)
 
     // write the data
     if (packet.count != 0) {
+        if (packet.count > sizeof(packet.data)) {
+            packet.count = sizeof(packet.data);
+        }
```
Comment (peterbarker) [inline libraries/GCS_MAVLink/GCS_serial_control.cpp:121]: I'm seriously not a fan of modifying these packets.  It's definitely not a pattern we use elsewhere.

I'd have perferred `const count = MIN(sizeof(packet.data), packet.count);

OTOH, I don't care that much :-)

**Review by peterbarker — APPROVED** [review]
LGTM

File: libraries/GCS_MAVLink/GCS_serial_control.cpp (hunk 1 above)
Comment (tpwrules) [reply libraries/GCS_MAVLink/GCS_serial_control.cpp:121]: Will keep this in mind in the future. We already reuse the packet for transmission below so storing into it is done in this function (for a different purpose!). This doesn't seem like the worst thing.
