### PR TITLE
SRV_Channel: native slew limiting

### LINKED ISSUE #14931: Plane: flap slew rate limit does not work for flaperons and d-spoilers
Flap slew-rate param only works for the dedicated flap and flap_auto servo functions. When flap is used in the flapperon and dspoiler mixer no slew rate is applied. 

Looks like a tricky fix, I think the best method would just be to refactor the slew rate servo channels function. The current function is only used by plane throttle and flaps.

### PR DESCRIPTION
**Pull request by IamPete1**
This turned into a bigger rework than I had expected. ~~The key change is that the function range / angle is now a property of the function not the channel it is assigned to. That then allowed native slew rate limiting.~~ Because the limiting is done at a scaled output level rather than PWM we can now slew limit to less than 1 us per loop and inherit limiting from other functions. 

This mean flaperons can now use flap slew rate Fixes #14931

~~I hope the flash cost is not too painful, were now storing more things per function rather than per channel.~~

### CODE REVIEW

**Comment by IamPete1** [comment]
I forgot the mention that this is a step towards removing the `read_last_sent` hal function, it was used the the old slew rate code. The only remaining user is the per motor compass cal. So this should be a step towards saving a little flash there.

File: ArduPlane/servos.cpp [hunk 1]
```diff
@@ -668,16 +666,15 @@ void Plane::set_servos_flaps(void)
         auto_flap_percent = manual_flap_percent;
     }
 
+    SRV_Channels::set_slew_rate(SRV_Channel::k_flap_auto, g.flap_slewrate, G_Dt);
+    SRV_Channels::set_slew_rate(SRV_Channel::k_flap, g.flap_slewrate, G_Dt);
```
Comment (IamPete1) [inline ArduPlane/servos.cpp:670]: No need for the reordering here

File: libraries/SRV_Channel/SRV_Channel_aux.cpp [hunk 2]
```diff
@@ -92,81 +92,6 @@ SRV_Channel::Aux_servo_function_t SRV_Channels::channel_function(uint8_t channel
     return SRV_Channel::k_none;
 }
 
-/*
-   setup a channels aux servo function
-*/
-void SRV_Channel::aux_servo_function_setup(void)
```
Comment (IamPete1) [inline libraries/SRV_Channel/SRV_Channel_aux.cpp:98]: this could stay and be passed the function like calc_pwm

File: libraries/SRV_Channel/SRV_Channel.h [hunk 3]
```diff
@@ -336,6 +320,32 @@ class SRV_Channel {
     void set_override(bool b) {override_active = b;};
 };
 
+class srv_function {
```
Comment (tridge) [inline libraries/SRV_Channel/SRV_Channel.h:323]: this is very ram expensive, about 3.5k with current functions, and will grow over time. That is too much on F405 boards for a little used feature. Almost certainly will break f103 AP_Periph PWM output too, it has very little ram
a pointer per function may be acceptable, or a bitmap of which functions have a slew rate, then a linked list or realloc list.

**Review by tridge — CHANGES_REQUESTED** [review]

File: libraries/SRV_Channel/SRV_Channel.h (hunk 3 above)
Comment (IamPete1) [reply libraries/SRV_Channel/SRV_Channel.h]: moved to a linked list

File: libraries/SRV_Channel/SRV_Channel_aux.cpp [hunk 4]
```diff
@@ -542,6 +542,24 @@ float SRV_Channels::get_output_scaled(SRV_Channel::Aux_servo_function_t function
     return 0;
 }
 
+float SRV_Channels::get_slew_limited_output_scaled(SRV_Channel::Aux_servo_function_t function)
```
Comment (tridge) [inline libraries/SRV_Channel/SRV_Channel_aux.cpp:545]: needs a comment

**Comment by tridge** [comment]
needs to be done for throttle too, which does this in servos.cpp:
```
    if (slewrate) {                   
        SRV_Channels::limit_slew_rate(func, slewrate, G_Dt);
    }
```

**Review by tridge — DISMISSED** [review]
needs to work for throttle (and left/right throttle)

**Comment by IamPete1** [comment]
Needs to set 0 slewrate in this early return. 

https://github.com/ArduPilot/ardupilot/blob/32488a5e3af018d7aa20e9139f7698713f405239/ArduPlane/servos.cpp#L34

File: libraries/SRV_Channel/SRV_Channel_aux.cpp (hunk 4 above)
Comment (IamPete1) [reply libraries/SRV_Channel/SRV_Channel_aux.cpp:546]: done

**Comment by IamPete1** [comment]
tested slew limiting still works for throttle and is correctly removed in manual throttle modes.

**Review by tridge — APPROVED** [review]
