### PR TITLE
AP_GPS_UBLOX: Fix GALILEO auto configuration

### LINKED ISSUE #13053: UBLOX galileo auto configuration not working reliably
I have two machines running **master** , both configured with GPS_GNSS_MODE = 71 , so GPS+SBAS+GLONASS+GALILEO should be enabled on the GPS units.

On the Beitian BN-880, running on **COPTER**, galileo gets enabled without any issue as I could have checked using serial passthrough after letting the FC configure the module:

image

On the Beitian BN-220, running on **PLANE**, galileo is **NOT** enabled.

image

If I disable auto configuration and manually enable it on the BN-220, the setting sticks, and galileo shows as enabled.

Both modules are running : u-blox 1 HW: 00080000 SW: ROM CORE 3.01 (107888)

Tridge suggested me to tag @WickedShell in order to have a look in this

I'm here ready to give every other needed detail and info.

### PR DESCRIPTION
**Pull request by giacomo892**
When Galileo GNSS is enabled in the configuration it is not actually enabled and the channels configuration is broken even if the GPS module ACK the configuration this fixes it.
I've tested on the modules u-blox modules I have.

After this by setting GPS_GNSS_MODE to 71 , ucenter reports this channel configuration
GNSS RESERVED MAX
GPS      4                 32
SBAS    1                   3
GALILEO 4               8
GLONASS 4           32

Fixes #13053

### CODE REVIEW

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 1]
```diff
@@ -981,17 +981,26 @@ AP_GPS_UBLOX::_parse_gps(void)
...
+
+                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId && GNSS_GALILEO !=_buffer.gnss.configBlock[i].gnssId) {
                             _buffer.gnss.configBlock[i].resTrkCh = (_buffer.gnss.numTrkChHw - 3) / (gnssCount * 2);
                             _buffer.gnss.configBlock[i].maxTrkCh = _buffer.gnss.numTrkChHw;
-                        } else {
-                            _buffer.gnss.configBlock[i].resTrkCh = 1;
-                            _buffer.gnss.configBlock[i].maxTrkCh = 3;
                         }
+                        else
+                        {
```
Comment (WickedShell) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:993]: Remove the extra line here.

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 2]
```diff
@@ -981,17 +981,26 @@ AP_GPS_UBLOX::_parse_gps(void)
...
                     }
                 }
-
                 for(int i = 0; i < _buffer.gnss.numConfigBlocks; i++) {
-                    // Reserve an equal portion of channels for all enabled systems
+                    // Reserve an equal portion of channels for all enabled systems that supports it
                     if(gps._gnss_mode[state.instance] & (1 << _buffer.gnss.configBlock[i].gnssId)) {
-                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId) {
+
+                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId && GNSS_GALILEO !=_buffer.gnss.configBlock[i].gnssId) {
```
Comment (WickedShell) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:988]: You only want to special case galileo if the hardware version is less then or equal to a M8, I need to validate it still, but I'd be surprised if the restriction still applies to the F9P and similar units.

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 3]
```diff
@@ -981,17 +981,26 @@ AP_GPS_UBLOX::_parse_gps(void)
...
                         }
+                        else
+                        {
+                            if(GNSS_SBAS ==_buffer.gnss.configBlock[i].gnssId) {
+                                _buffer.gnss.configBlock[i].resTrkCh = 1;
+                                _buffer.gnss.configBlock[i].maxTrkCh = 3;
+                            }
+                            if(GNSS_GALILEO ==_buffer.gnss.configBlock[i].gnssId) {
+                                _buffer.gnss.configBlock[i].resTrkCh = (_buffer.gnss.numTrkChHw - 3) / (gnssCount * 2);
+                                _buffer.gnss.configBlock[i].maxTrkCh = 8; //3.01 accepts max 10 ch even if it ACK every setting above it we send, let's stay safe with 8
```
Comment (WickedShell) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:1000]: I'd change the comment here to say something along the lines of "Per the M8 receiver description UBX-13003221 - R16, 4.1.1.3 it is not recommended to set the number of galileo channels higher then eight"

**Comment by giacomo892** [comment]
@WickedShell Thanks for the review. 
I should have addressed your comments by applying the patch only if we do not detect an UBLOX F9 or newer.

**Comment by anbello** [comment]
Thanks to @giacomo892 this fix will be really useful for people living in Europe.

**Comment by anbello** [comment]
I tested this PR yesterday on my copter with SAM-M8Q GPS.

First on workbench and I saw that with GPS_GNSS_MODE = 71 I have (in u-center):
GNSS RESERVED MAX
GPS 4 32
SBAS 1 3
GALILEO 4 8
GLONASS 4 32

Then on field and I saw NSats = 19, HDop = 0.63 and Status = 4 (3D Fix + DGPS).

**Comment by anbello** [comment]
Tested also on copter with Pixracer and BN-880 GPS.

NSats = 26, HDop = 0.49 and Status = 4 (3D Fix + DGPS).

**Comment by andyp1per** [comment]
@khancyr what was the status on this?

**Comment by albertocopter** [comment]
Thanks to @giacomo892 this fix will be really useful for people living in Europe.
GPS_GNSS_MODE = 71, RATE 10Hz, protcol UBLOX.
Copter FC Omnibus F4 nano V6.0 BN220 GPS
Then on field and I saw NSats = 16, HDop = 0.8

**Comment by amilcarlucas** [comment]
Looks like this has been tested. Should we remove the "needs testing" label and add the DevCallEu label?

**Comment by skorokithakis** [comment]
Was this discussed in today's call? What was the outcome?

**Comment by giacomo892** [comment]
> Was this discussed in today's call? What was the outcome?

Looks like it was not. Out of time

**Comment by khancyr** [comment]
No, we didn't had time this week

**Comment by skorokithakis** [comment]
Could this be tagged for the DevCall?

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 4]
```diff
@@ -1942,3 +1950,9 @@ bool AP_GPS_UBLOX::supports_F9_config(void) const
 {
     return _hardware_generation == UBLOX_F9 && _hardware_generation != UBLOX_UNKNOWN_HARDWARE_GENERATION;
 }
+
+// return true if GPS is an uBlox M9
+bool AP_GPS_UBLOX::is_ublox_M9(void) const
```
Comment (peterbarker) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:1955]: We should be checking for capability/requirements rather than device model.

**Comment by peterbarker** [comment]
We need @WickedShell to OK this

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 5]
```diff
@@ -981,17 +981,25 @@ AP_GPS_UBLOX::_parse_gps(void)
...
-                            _buffer.gnss.configBlock[i].resTrkCh = 1;
-                            _buffer.gnss.configBlock[i].maxTrkCh = 3;
                         }
+                        else {
+                            if(GNSS_SBAS ==_buffer.gnss.configBlock[i].gnssId) {
+                                _buffer.gnss.configBlock[i].resTrkCh = 1;
+                                _buffer.gnss.configBlock[i].maxTrkCh = 3;
+                            }
+                            if( (!supports_F9_config() || !is_ublox_M9()) && GNSS_GALILEO ==_buffer.gnss.configBlock[i].gnssId) {
+                                _buffer.gnss.configBlock[i].resTrkCh = (_buffer.gnss.numTrkChHw - 3) / (gnssCount * 2);
```
Comment (tridge) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:998]: the logic (!supports_F9_config() || !is_ublox_M9()) means it will do this logic for F9, should this be an && not an || ?

**Review by tridge — CHANGES_REQUESTED** [review]

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp (hunk 5 above)
Comment (giacomo892) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:996]: Address this. It will impact only <=M8 as now leaving the behaviour unchanged for the rest. Please merge if you are comfortable with this. Thanks

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 6]
```diff
@@ -979,17 +979,25 @@ AP_GPS_UBLOX::_parse_gps(void)
...
                     }
                 }
-
                 for(int i = 0; i < _buffer.gnss.numConfigBlocks; i++) {
-                    // Reserve an equal portion of channels for all enabled systems
+                    // Reserve an equal portion of channels for all enabled systems that supports it
                     if(gps._gnss_mode[state.instance] & (1 << _buffer.gnss.configBlock[i].gnssId)) {
-                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId) {
+
+                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId && (supports_F9_config() || is_ublox_M9() || GNSS_GALILEO !=_buffer.gnss.configBlock[i].gnssId)) {
```
Comment (WickedShell) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:986]:
```suggestion
                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId && (_hardware_generation > UBLOX_M8 || GNSS_GALILEO !=_buffer.gnss.configBlock[i].gnssId)) {
```

Why not structure it more like this? The problem with the f9 config/m9 config is you are comitting to a course that requires future updates everytime a new module is shipped, whereas if you just check for anything newer/older then the M8 as your baseline point.... I don't think we benefit by proliferating helpers into this.

**Review by WickedShell — CHANGES_REQUESTED** [review]

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 7]
```diff
@@ -979,17 +979,25 @@ AP_GPS_UBLOX::_parse_gps(void)
...
-                        } else {
-                            _buffer.gnss.configBlock[i].resTrkCh = 1;
-                            _buffer.gnss.configBlock[i].maxTrkCh = 3;
                         }
+                        else {
+                            if(GNSS_SBAS ==_buffer.gnss.configBlock[i].gnssId) {
+                                _buffer.gnss.configBlock[i].resTrkCh = 1;
+                                _buffer.gnss.configBlock[i].maxTrkCh = 3;
+                            }
+                            if( (!supports_F9_config() && !is_ublox_M9()) && GNSS_GALILEO ==_buffer.gnss.configBlock[i].gnssId) {
```
Comment (WickedShell) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:995]: Why do you have to check the version again here? It should be the only way we get to this path....

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp (hunk 4 above)
Comment (WickedShell) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:1953]: Agreed, this helper should go away.

**Comment by giacomo892** [comment]
Thanks @WickedShell and @peterbarker for the reviews.
I have addressed everything and tested it. Can you add a dev call tag so we finally get this in after more than a year :) ?

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 8]
```diff
@@ -979,16 +979,22 @@ AP_GPS_UBLOX::_parse_gps(void)
                         gnssCount++;
                     }
                 }
-
                 for(int i = 0; i < _buffer.gnss.numConfigBlocks; i++) {
-                    // Reserve an equal portion of channels for all enabled systems
+                    // Reserve an equal portion of channels for all enabled systems that supports it
                     if(gps._gnss_mode[state.instance] & (1 << _buffer.gnss.configBlock[i].gnssId)) {
-                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId) {
+                        if(GNSS_SBAS !=_buffer.gnss.configBlock[i].gnssId && (_hardware_generation > UBLOX_M8 || GNSS_GALILEO !=_buffer.gnss.configBlock[i].gnssId)) {
```
Comment (peterbarker) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:985]: This will still modify behaviour on non-M8

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 9]
```diff
@@ -979,16 +979,22 @@ AP_GPS_UBLOX::_parse_gps(void)
...
                             _buffer.gnss.configBlock[i].resTrkCh = (_buffer.gnss.numTrkChHw - 3) / (gnssCount * 2);
                             _buffer.gnss.configBlock[i].maxTrkCh = _buffer.gnss.numTrkChHw;
-                        } else {
-                            _buffer.gnss.configBlock[i].resTrkCh = 1;
-                            _buffer.gnss.configBlock[i].maxTrkCh = 3;
+                        }
+                        else {
```
Comment (peterbarker) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:989]:
```suggestion
                        } else {
```

**Review by peterbarker — CHANGES_REQUESTED** [review]

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp (hunk 8 above)
Comment (tridge) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:985]: this still changes behaviour on F9 depending on the contents of configBlock

**Review by tridge — CHANGES_REQUESTED** [review]

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp [hunk 10]
```diff
@@ -979,16 +979,22 @@ AP_GPS_UBLOX::_parse_gps(void)
...
+                            if(GNSS_SBAS ==_buffer.gnss.configBlock[i].gnssId) {
```
Comment (muramura) [inline libraries/AP_GPS/AP_GPS_UBLOX.cpp:990]: The ArduPilot has a coding style.
For example, an if statement is if () { with a space between.
I think it is better to match the coding style.

https://ardupilot.org/dev/docs/style-guide.html

Comment (skorokithakis) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:990]: As an aside, it's a huge pet peeve of mine that this is not automatically applied.

Comment (muramura) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:990]: There are commands to automatically convert sources to coding styles and their definition files.
Once this PR was merged, I wanted to convert the format with this command and PR it again.
astyle --options=Tools/CodeStyle/astylerc <filename>

Comment (skorokithakis) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:990]: Yes, but the entire codebase isn't automatically formatted, and if you change a line in a file and run the formatter, the diff is ruined.

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp (hunk 8 above)
Comment (giacomo892) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:985]: This is as intended. 
Hardware > M8 will keep the previous behaviour, aka allocate the channels as it was in the past. Basically everything newer than M8 will go into the else only for configuring SBAS. Am I reading it wrong?

Comment (giacomo892) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp:985]: Thanks. See the comment I left on Peter's

**Review by tridge — APPROVED** [review]

File: libraries/AP_GPS/AP_GPS_UBLOX.cpp (hunk 7 above)
Comment (giacomo892) [reply libraries/AP_GPS/AP_GPS_UBLOX.cpp]: Fixed
