### PR TITLE
AP_Logger: log transfer: add error message if armed

### LINKED ISSUE #8914: Rover: improved error message when log download fails because vehicle is armed
With Rover's it's quite common for users to try and download a log while the vehicle is armed.  The failure (viewed in MP) does not make it very clear that this is the issue.  I'm unsure if it's a mission planner issue or an ArduPilot issue but I'm adding it here in any case.

### PR DESCRIPTION
**Pull request by IamPete1**
Fixes #8914

This is used on all vehicles, although the issue is just for rover.

Currently log related mavlink stuff will silently fail if armed. Will also fail if `!WritesEnabled()` but in that case AP will be printing "Initialising ArduPilot" every 5 seconds, so I don't think we need another message.

### CODE REVIEW

**Comment by IamPete1** [comment]
Note that if you arm during a log download the GCS might keep trying (MAVProxy does), in which case this message is printed a lot.  Maybe we should be refusing to arm in log download.

**Comment by IamPete1** [comment]
Added a arming check for log downloading.

File: libraries/AP_Arming/AP_Arming.cpp [hunk 1]
```diff
@@ -260,6 +260,10 @@ bool AP_Arming::logging_checks(bool report)
             check_failed(ARMING_CHECK_LOGGING, report, "No SD card");
             return false;
         }
+        if (AP::logger().in_log_download()) {
+            check_failed(ARMING_CHECK_LOGGING, report, "Downloading logs");
```
Comment (tridge) [inline libraries/AP_Arming/AP_Arming.cpp:264]: better to only output msg once per arming

**Review by tridge — CHANGES_REQUESTED** [review]

**Comment by IamPete1** [comment]
Now will only send one message warning to disarm for logging.

**Review by tridge — APPROVED** [review]
