### PR TITLE
Plane: fixed LOITER_TO_ALT with terrain target

### LINKED ISSUE #14951: Plane: auto mode loiter to alt uses incorrect reference frame to trigger completed
When using terrain following in auto loiter to alt works as expected, however the altitude relative to origin is used for the threshold rather than relative to terrain. This results in a endless loiter.

https://github.com/ArduPilot/ardupilot/blob/8f77536c08af9ffc01334736c92bb25be4c563e2/ArduPlane/navigation.cpp#L56

In that case should be using height above terrain rather than current_loc.alt. However are also other reference frames the mission could be using that would cause the same issue.  

I have a log, but cannot share publicity.

### PR DESCRIPTION
**Pull request by tridge**
many thanks to Pompecukor for finding this!

Fixes #14951

### CODE REVIEW

**Comment by pompecukor** [comment]
Tested on Plane, working perfectly. Logs sent to Andrew. Thank you.

(the same exact -real- mission was flow which was giving the issue related to this. Now it was working as desired)

File: ArduPlane/navigation.cpp [hunk 1]
```diff
@@ -53,7 +54,24 @@ void Plane::loiter_angle_update(void)
...
+    /*
+      if doing terrain following then check against terrain target
+     */
+    bool reached_target_alt = false;
+#if AP_TERRAIN_AVAILABLE
+    float altitude_agl;
+    if (reached_target && target_altitude.terrain_following &&
+        terrain.status() == AP_Terrain::TerrainStatusOK &&
+        terrain.height_above_terrain(altitude_agl, true) &&
+        fabsf(altitude_agl - target_altitude.terrain_alt_cm*0.01) < 5) {
```
Comment (peterbarker) [inline ArduPlane/navigation.cpp:66]: Something doesn't look right here.

In the case that we are flying terrain and we are able to retrieve a terrain-altitude *and* we haven't yet reached that terrain altitude.... we then go and check to see if we have reached our target amsl.  Surely we should accept we haven't reached the terrain altitude yet and keep flying up or down?

i.e. we need another "if" here and one less `&&`.
