### PR TITLE
GPS: update SwiftBinary Protocol (SBPv2) parser to match docs more closely

### LINKED ISSUE #10229: GPS: SBP2 GPS messages not recognized
### Bug report

**Issue details**

Recent versions of SwiftNav's SBP protocol (SBP2 GPS driver in Ardupilot) report an additional GPS fix type "[SBAS](https://en.wikipedia.org/wiki/GNSS_augmentation)", which the current Ardupilot driver doesn't know about.  This leads Ardupilot to ignore GPS data from the swiftnav GPS unit, because it interprets that unknown fix type as bad data (or just a missing fix).

[SwiftNav's protocol with updated field](https://github.com/swift-nav/libsbp/blob/e18d5474b91a6dc93bc02b2b4ade8063643fff10/spec/yaml/swiftnav/sbp/navigation.yaml#L192)
[SwiftNav PR](https://github.com/swift-nav/libsbp/pull/553)
[SwiftNav SBP docs](https://github.com/swift-nav/libsbp/blob/master/docs/sbp.pdf)

We detected this issue a couple of months ago and I wrote some basic updates to the driver, but we've been using a workaround for the last couple of months, so I haven't had time to test whether the updated driver works or not.   I'm hoping to get to this next week, and hopefully submit a PR at that time, but figured I'd go ahead and file an issue 1) in case anyone else is having problems, and 2) to help keep me honest about finishing and contributing the updates back.

**Version**
Rover 3.4.?

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

### PR DESCRIPTION
**Pull request by bk-mtg**
A number of misc fixes here to make the typedefs etc match the documentation more closely, but most importantly this teaches the driver about fix_type=6 (SBAS).

This PR fixes #10229.

### CODE REVIEW

File: libraries/AP_GPS/AP_GPS_SBP2.cpp [hunk 1]
```diff
@@ -333,6 +333,7 @@ AP_GPS_SBP2::_attempt_state_update()
             case 1:
                 state.status = AP_GPS::GPS_OK_FIX_3D;
                 break;
+            case 6:
```
Comment (bk-mtg) [inline libraries/AP_GPS/AP_GPS_SBP2.cpp]: This adds the SBAS fix as a 'DGPS' 3D fix.  It might also be appropriate to add it with case 1 above (as just a regular 3D fix) instead?

**Comment by bk-mtg** [comment]
Interesting; I apparently should've looked more closely.  The main "bug" fix here appears to have already been addressed in f67a9af3.

File: libraries/AP_GPS/AP_GPS_SBP2.h [hunk 2]
```diff
@@ -128,9 +129,9 @@ class AP_GPS_SBP2 : public AP_GPS_Backend
         uint16_t v_accuracy;  //< Vertical position accuracy estimate (unit: mm)
         uint8_t n_sats;       //< Number of satellites used in solution
         struct PACKED flags {
-            uint8_t fix_mode:3;  //< Fix mode (0: invalid, 1: SPP, 2: DGNSS, 3: Float RTX, 4: Fixed RTX
-            uint8_t res:4;       //< Reserved
-            bool raim_repair:1;  //< Solution from RAIM?
+            uint8_t fix_mode:3;  //< Fix mode (0: invalid, 1: SPP, 2: DGNSS, 3: Float RTX, 4: Fixed RTX, 5: Dead Reckoning, 6: SBAS Position
+            uint8_t in_mode:2;   //< Inertial navigation mode (0: none, 1: INS used)
```
Comment (OXINARF) [inline libraries/AP_GPS/AP_GPS_SBP2.h]: This should probably be called `ins_mode`.

File: libraries/AP_GPS/AP_GPS_SBP2.h [hunk 3]
```diff
@@ -144,8 +145,9 @@ class AP_GPS_SBP2 : public AP_GPS_Backend
         uint16_t v_accuracy;   //< Vertical velocity accuracy estimate (unit: mm/s)
         uint8_t n_sats;        //< Number of satellites used in solution
         struct PACKED flags {
-            uint8_t fix_mode:3;  //< Fix mode (0: invalid, 1: SPP, 2: DGNSS, 3: Float RTX, 4: Fixed RTX
-            uint8_t res:5;       //< Reserved
+            uint8_t vel_mode:3;  //< Velocity mode (0: Invalid, 1: Measured Doppler derived, 2: Computed Doppler derived, 3: Dead reckoning)
+            uint8_t in_mode:2;   //< Inertial navigation mode (0: none, 1: INS used)
```
Comment (OXINARF) [inline libraries/AP_GPS/AP_GPS_SBP2.h]: Same.

**Comment by njoubert** [comment]
Hi folks! This looks good to me. Our Applications Engineer, Sarika, will also take a look, she's maintaining many of these drivers for us now. @swiftnav-sarika wanna take a look?

**Comment by OXINARF** [comment]
Merged, thanks!
