### PR TITLE
Copter: allow mid stick arming

### LINKED ISSUE #18692: AC4.1.0-rc2  arming failure due to "PreArm: Throttle (RC3) is not neutral"
## Bug report

This is on a 3DR Solo (Throttle stick configured to be in center)
When arming via command (long press "FLY" button) "PreArm: Throttle (RC3) is not neutral"
 pops up unless I hold the Throttle stick down.

PILOT_THR_BHV    7
RC3_DZ           30
RC3_MAX          1890
RC3_MIN          1008
RC3_TRIM         1450

The TLOG demonstrates the issue very well.

**Version**
AC4.1.0-rc2  , OpenSolo 4.0

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
X 

**Hardware type**
CubeSolo , SoloController with spring-loaded, centering throttle.

**Logs**
_Please provide a link to any relevant logs that show the issue
[logs.zip](https://github.com/ArduPilot/ardupilot/files/7186513/logs.zip)
_

### PR DESCRIPTION
**Pull request by IamPete1**
Fixes #18692

This skips  the AP_Arming throttle check if PILOT_THR_BHV bit "Feedback from mid stick" is set. This is used as a center throttle flag on for landing detection.

Copters own throttle arming checks are quite comprehensive, we might want to skip the AP_Arming one in all cases.

### CODE REVIEW

File: ArduCopter/RC_Channel.cpp [hunk 1]
```diff
@@ -48,6 +48,13 @@ bool RC_Channels_Copter::has_valid_input() const
     return true;
 }
 
+bool RC_Channels_Copter::arming_check_throttle() const {
```
Comment (rmackay9) [inline ArduCopter/RC_Channel.cpp:51]: Let's put some comments somewhere.. nothing long and wordy but a quick description of what it's doing will be helpful for the next dev who treads over this path.

**Comment by rmackay9** [comment]
.. and the regular question, "what testing has been done?"... I guess you've probably reproduced the problem and checked that this resolves it... and probably also checked that normal non-mid-stick arming check still works?

File: ArduCopter/RC_Channel.cpp (hunk 1 above)
Comment (IamPete1) [reply ArduCopter/RC_Channel.cpp:52]: done

**Comment by IamPete1** [comment]
@rmackay9 yep, reproduced and checked. As I said the copter checks catch it fine if your above mid. Still need min in stabilize.

File: ArduCopter/RC_Channel.h [hunk 2]
```diff
@@ -42,6 +42,9 @@ class RC_Channels_Copter : public RC_Channels
         return &obj_channels[chan];
     }
 
+    // allow disabling AP_Arming throttle check
```
Comment (rmackay9) [inline ArduCopter/RC_Channel.h:45]: not a big deal but this should probably be, "returns true if throttle arming checks should be run".. not a blocker though!

**Review by rmackay9 — APPROVED** [review]
Great, thanks for this!

File: ArduCopter/RC_Channel.cpp [hunk 3]
```diff
@@ -48,6 +48,16 @@ bool RC_Channels_Copter::has_valid_input() const
     return true;
 }
 
+// allow disabling AP_Arming throttle check
+bool RC_Channels_Copter::arming_check_throttle() const {
+    if ((copter.g.throttle_behavior & THR_BEHAVE_FEEDBACK_FROM_MID_STICK) != 0) {
```
Comment (peterbarker) [inline ArduCopter/RC_Channel.cpp:53]: I wonder if we should make a virtual method which returns this information instead of the approach taken here.

That would allow Plane to provide the same information to allow sprung-throttle arming.

**Review by peterbarker — APPROVED** [review]
Thanks - I'd noticed this same problem several months back!

File: ArduCopter/RC_Channel.cpp (hunk 3 above)
Comment (IamPete1) [reply ArduCopter/RC_Channel.cpp:53]: This only works because Copter is already doing throttle checks, so were not skipping all throttle checks. I suspect the real solution is to move copters throttle checks up and then we could do a virtual vehicle method as you suggest.

File: ArduCopter/RC_Channel.h (hunk 2 above)
Comment (IamPete1) [reply ArduCopter/RC_Channel.h]: fixed
