### PR TITLE
AP_Scheduler: corrected tick counter overflow handling, fixes #17642

### LINKED ISSUE #17642: AP_Scheduler: tasks scheduled prematurely every ~163 seconds with a 400 Hz main loop
## Bug report

**Issue details**

The scheduler class executes all tasks before their time is due every ~163 seconds on ArduCopter 4.x. This can easily be tested in the SITL by setting `SCHED_DEBUG` to 3 and then watching for `Scheduler slip task` messages on the (simulated) UART; every ~163 seconds there is a stream of messages like this:

```
Scheduler slip task[0-rc_loop] (4294901764/4/130)
Scheduler slip task[1-throttle_loop] (4294901768/8/75)
Scheduler slip task[2-update_GPS] (4294901768/8/200)
Scheduler slip task[3-update] (4294901762/2/160)
...
Scheduler slip task[46-terrain_update] (4294901776/40/100)
Scheduler slip task[47-update] (4294901776/40/75)
Scheduler slip task[48-update] (4294901776/80/100)
...
```

Note the incorrect `dt` value, which is very close to 2^32 in all cases. This is actually the root cause of the issue; `dt` was changed from an `uint16_t` to an `uint32_t` between ArduCopter 3.x and 4.x, so it no longer handles the overflow of the 16-bit tick counter correctly. (At least not with my C compiler).

You may also notice the bug from the `PERF` warning messages in the MAVLink stream if you don't have access to the debug console; every 163 seconds there will be a `PERF` message where the number of loops executed since the last message will not be around 4000 (as expected for a 400 Hz loop every 10 seconds) but 1536; note that 65536 - 16*4000 = 1536.

**Version**

ArduCopter 4.0.7, but it affects all versions from 4.0.0. Versions in the 3.x series are not affected.

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

Not applicable.

**Hardware type**

Tested on a Pixhawk1 and on a CubeBlack with stock firmware; same issue, but the reproduction is easier in the SITL.

**Logs**

Not applicable.

### PR DESCRIPTION
**Pull request by ntamas**
This PR fixes the issue outlined with the task scheduler in #17642.

Right now the scheduler will prematurely schedule all tasks at the same time every 65536 ticks (~163 seconds on a 400 Hz loop). The PR fixes the problem by reverting the type of the tick count difference variables to `uint16_t` from `uint32_t`.

A more detailed description of the problem (along with symptoms) is in #17642.

### CODE REVIEW

File: libraries/AP_Scheduler/AP_Scheduler.cpp [hunk 1]
```diff
@@ -160,9 +160,9 @@ void AP_Scheduler::run(uint32_t time_available)
     for (uint8_t i=0; i<_num_tasks; i++) {
         const AP_Scheduler::Task& task = (i < _num_unshared_tasks) ? _tasks[i] : _common_tasks[i - _num_unshared_tasks];
 
-        uint32_t dt = _tick_counter - _last_run[i];
+        uint16_t dt = _tick_counter - _last_run[i];
```
Comment (peterbarker) [inline libraries/AP_Scheduler/AP_Scheduler.cpp:163]:
```suggestion
        const uint16_t dt = _tick_counter - _last_run[i];
```

File: libraries/AP_Scheduler/AP_Scheduler.cpp [hunk 2]
```diff
@@ -160,9 +160,9 @@ void AP_Scheduler::run(uint32_t time_available)
...
         // we allow 0 to mean loop rate
-        uint32_t interval_ticks = (is_zero(task.rate_hz) ? 1 : _loop_rate_hz / task.rate_hz);
+        uint16_t interval_ticks = (is_zero(task.rate_hz) ? 1 : _loop_rate_hz / task.rate_hz);
```
Comment (peterbarker) [inline libraries/AP_Scheduler/AP_Scheduler.cpp:165]: Pretty sure this patch isn't required.  Someone running their loops *much* faster than the slowest task might end up getting problems in here.  e.g. `_loop_rate_hz` of 1000 and a `task.rate_hz` of 1/60 gives an interval_ticks of 60,000 - perilously close the uint16-max.  I think we can afford to burn an extra 2 bytes on the stack here :-)

**Review by peterbarker — CHANGES_REQUESTED** [review]

File: libraries/AP_Scheduler/AP_Scheduler.cpp (hunk 2 above)
Comment (ntamas) [reply libraries/AP_Scheduler/AP_Scheduler.cpp:165]: I wasn't sure about this change either; I changed the `uint32_t` to `uint16_t` for sake of consistency with `dt`.

One thing is sure: with the current scheduler architecture, we cannot schedule tasks with an interval larger than 65535 ticks anyway because the tick counter is 16-bit. Therefore,

* If we keep `interval_ticks` as `uint32_t`, it will always be larger than the maximum possible value of `dt` for such tasks if `dt` is 16-bit, so tasks would never get scheduled.
* If we convert `interval_ticks` to `uint16_t`, it could potentially overflow for such rarely-scheduled tasks, and it could potentially overflow in a way that the task gets scheduled much more frequently than expected.

So, it seems like `uint32_t` is safer as we don't cause extra CPU load even if the user misconfigures the loop.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@ntamas thanks!

**Review by peterbarker — APPROVED** [review]

**Review by peterbarker — DISMISSED** [review]
Sorry, we need to squash all those commits together.  Just fixup the second two into the first.

Tried to it for you, but permission was denied on your branch.

**Comment by ntamas** [comment]
Not sure why it was denied on my branch or where I could enable it, but I've squashed the commits and rebased it on top of master so I hope it's good to go now.

**Comment by peterbarker** [comment]
Merged, thanks!

In terms of the fail-to-push thing, that was perhaps (a) me screwing up or (b) you unchecked the box allowing pushes from maintainers to your branch.  I think it can also happen with private repos or something in github.

In any case, thanks for this great fix!

**Comment by ntamas** [comment]
Figured it out: the checkbox that allows pushes for maintainers is apparently not visible if the branch being pulled from belongs to an organization account. The checkbox is there if I make a PR from my own account but not from an organization account.

Anyhow, thanks for merging this!
