### PR TITLE
Filter: fixed crash on zero cutoff frequency

### LINKED ISSUE #10435: Division-by-zero error for two filter parameters
### Bug report

**Issue details**
If I put some value larger than or equal to 0 and lower than 1 on INS_GYRO_FILTER or INS_ACCEL_FILTER, ArduPilot will crash due to division by zero.
I got the following message with GDB.

Program received signal SIGFPE, Arithmetic exception.
in LowPassFilter2p<Vector3<float> >::set_cutoff_frequency(float, float) ()

**Version**
3.5.7

**Platform**
[  ] All
[  ] AntennaTracker
[O] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
But, other platforms must share the same problems

**Airframe type**
Quadcopter but applicable to other frames

**Hardware type**
I checked this bug only on SITL

### PR DESCRIPTION
**Pull request by tridge**
this fixes #10435 
ping @peterbarker

### CODE REVIEW

File: libraries/Filter/LowPassFilter2p.cpp [hunk 1]
```diff
@@ -83,6 +87,10 @@ float LowPassFilter2p<T>::get_sample_freq(void) const {
 
 template <class T>
 T LowPassFilter2p<T>::apply(const T &sample) {
+    if (!is_positive(_params.cutoff_freq)) {
```
Comment (peterbarker) [inline libraries/Filter/LowPassFilter2p.cpp]: Applying this to https://github.com/ardupilot/ardupilot/blob/master/libraries/Filter/LowPassFilter.cpp#L104 might make that clearer, too.

Comment (tridge) [reply libraries/Filter/LowPassFilter2p.cpp]: LowPassFilter.cpp already handles this case
