### PR TITLE
Fix ground effect compensation

### LINKED ISSUE #17552: Ground Effect Compensation broken in EKF3 (and probably EKF2)
This PR https://github.com/ArduPilot/ardupilot/pull/15665 broke ground effect compensation by reducing the frequency with which the vehicle code calls EKF2 and EKF3's setTakeoffExpected() and setTouchdownExpected methods are called

Before the change the EKFs were always called, afterwards the early return means they are only called when the state is changed.  What was misunderstood however is that the EKFs have a one second timeout meaning that if they are not called continuously with "true" they revert to "false".

By the way, the current state of the two flags can be seen by looking in the XKF4.SS field and check bits 11 and 12.

### PR DESCRIPTION
**Pull request by peterbarker**
Closes #17552 

Apart from the autotest I've added here, I've manually reviewed the logs produced by the autotest to ensure the flag continues to be set as appropriate.

I've also tested quadplane before/after this patch.  Before the patch the ground effect compensation was only turned on for a second (the predicted broken behaviour), after the fix it remained on for ~20 seconds while the vehicle was `QLAND`ing.

The solution here effectively decimates the messages we pass down to the EKFs.  I would have actually preferred to eliminate the timeout of the state down in the EKF, but quadplane's structure means this would be rather involved.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks very much for this!

I'm not a big fan though of creating another parallel timer in AP_AHRS_NavEKF because I think this adds more complexity and thus more chance for bugs in the future.

How about if we move the timers out of the individual cores and put them way up at the AP_AHRS or AP_AHRS_NavEKF level?  So we don't trust the vehicles to constantly call the setTakeoffExpected, etc but remove the parallel timers way down in the individual cores.  I'm pretty sure the timeout shouldn't come from the cores themselves.

**Comment by peterbarker** [comment]
> Thanks very much for this!
> 
> I'm not a big fan though of creating another parallel timer in AP_AHRS_NavEKF because I think this adds more complexity and thus more chance for bugs in the future.
> 
> How about if we move the timers out of the individual cores and put them way up at the AP_AHRS or AP_AHRS_NavEKF level? So we don't trust the vehicles to constantly call the setTakeoffExpected, etc but remove the parallel timers way down in the individual cores. I'm pretty sure the timeout shouldn't come from the cores themselves.

I'm not sure how we can move those timers up to `AP_AHRS_NavEKF` as the getters within (e.g.)AP_NavEKF3 are the ones actually doing the timeout check.  i.e. they're not leaving AP_NavEKF3 to check the validity of the flag (and nor should they).

We can redo this to remove the timers - but QuadPlane is going to be an involved patch (c.f. this one which is pretty straight forward).  I just had a look at this and the flags in the two different EKF2s are interestingly and subtly different.

**Comment by priseborough** [comment]
I'm OK with handling the EKF requirement for regular poking in the AHRS provided the requirement is clearly documented at in EKF interface, eg:

https://github.com/priseborough/ardupilot/commit/6060bc9e56181ddcb41068680a18342f7a6b9bd4
https://github.com/priseborough/ardupilot/commit/61a4f971dfa5730dfb87354b5c18f87d86543141

**Review by priseborough — CHANGES_REQUESTED** [review]
@peterbarker 

Pull in https://github.com/priseborough/ardupilot/commit/6060bc9e56181ddcb41068680a18342f7a6b9bd4 and https://github.com/priseborough/ardupilot/commit/61a4f971dfa5730dfb87354b5c18f87d86543141

and it's a workable solution from my perspective.

**Comment by tridge** [comment]
@priseborough @peterbarker I have reworked this now so the state and timeout is handled at the AHRS level. This makes the code much simpler

**Comment by tridge** [comment]
@priseborough I am concerned about hand-launching gliders off a cliff. It looks like we would prevent baro detection of descent
I'm also concerned about when throw mode is used for a drop off a bridge

**Comment by tridge** [comment]
@priseborough I added a check for fly forward to the baro measurement MAX() calls

**Comment by tridge** [comment]
had a good flight on fixed wing with this yesterday:
http://uav.tridgell.net/NanoTalon/2021-05-30/log144.bin
also flew on a 6" quad:
http://uav.tridgell.net/BraveHeart/2021-05-30/log74.bin
baro compensation worked nicely on takeoff:
image

**Comment by tridge** [comment]
> @peterbarker
> 
> Pull in [priseborough@6060bc9](https://github.com/priseborough/ardupilot/commit/6060bc9e56181ddcb41068680a18342f7a6b9bd4) and [priseborough@61a4f97](https://github.com/priseborough/ardupilot/commit/61a4f971dfa5730dfb87354b5c18f87d86543141)
> 
> and it's a workable solution from my perspective.

those comments no longer apply with the new implementation as timout is in AP_AHRS

File: libraries/AP_AHRS/AP_AHRS_DCM.cpp [hunk 1]
```diff
@@ -116,6 +116,9 @@ AP_AHRS_DCM::update(bool skip_ins_update)
     update_AOA_SSA();
 
     backup_attitude();
+
+    // update takeoff/touchdown flags
+    update_flags();
```
Comment (rmackay9) [inline libraries/AP_AHRS/AP_AHRS_DCM.cpp:121]: I find it a bit sad that the general purpose AHRS::update() is in AP_AHRS_DCM.  This is correct though right, this is the only place we can put it?

File: libraries/AP_AHRS/AP_AHRS.h [hunk 2]
```diff
@@ -649,6 +661,8 @@ class AP_AHRS
         uint8_t fly_forward             : 1;    // 1 if we can assume the aircraft will be flying forward on its X axis
         uint8_t correct_centrifugal     : 1;    // 1 if we should correct for centrifugal forces (allows arducopter to turn this off when motors are disarmed)
         uint8_t wind_estimation         : 1;    // 1 if we should do wind estimation
+        uint8_t takeoff_expected        : 1;    // 1 if the vehicle is in a state that takeoff might be expected.  Ground effect may be in play.
+        uint8_t touchdown_expected       : 1;    // 1 if the vehicle is in a state that touchdown might be expected.  Ground effect may be in play.
```
Comment (rmackay9) [inline libraries/AP_AHRS/AP_AHRS.h:665]: nitpick: there's a 1 space error in whitespace before the comment.

File: libraries/AP_AHRS/AP_AHRS_DCM.cpp (hunk 1 above)
Comment (tridge) [reply libraries/AP_AHRS/AP_AHRS_DCM.cpp:121]: we could refactor it, but with our current structure that is the logical place

File: libraries/AP_DAL/AP_DAL.h [hunk 3]
```diff
@@ -173,6 +173,17 @@ class AP_DAL {
...
+    bool get_takeoff_expected(void) const {
+        return _RFRN.takeoff_expected;
+    }
+
+    bool get_touchdown_expected(void) const {
+        return _RFRN.touchdown_expected;
+    }
+
+    // for EKF usage to enable takeoff expected
+    void set_takeoff_expected();
```
Comment (rmackay9) [inline libraries/AP_DAL/AP_DAL.h:185]: I wonder if this is confusing to have two versions of this parameter.. maybe rename to "set_takeoff_expected_to_true()"?

File: libraries/AP_DAL/AP_DAL.cpp [hunk 4]
```diff
@@ -99,6 +101,15 @@ void AP_DAL::start_frame(AP_DAL::FrameType frametype)
 #endif
 }
 
+// for EKF usage to enable takeoff expected
```
Comment (rmackay9) [inline libraries/AP_DAL/AP_DAL.cpp:104]: ... or maybe we should change this comment to "set takeoff expected to true"

Comment (tridge) [reply libraries/AP_DAL/AP_DAL.cpp]: done

File: libraries/AP_DAL/AP_DAL.h (hunk 3 above)
Comment (tridge) [reply libraries/AP_DAL/AP_DAL.h:185]: i did the comment change instead

File: libraries/AP_AHRS/AP_AHRS.h (hunk 2 above)
Comment (tridge) [reply libraries/AP_AHRS/AP_AHRS.h]: fixed

**Comment by rmackay9** [comment]
I've checked the flags and they seem to be being set correctly.  This is a screenshot of the flags and altitude in a simple test where I took off in Loiter, flew forward a bit and then engaged RTL.
gndeff-takeoff-landing-flags

**Review by rmackay9 — APPROVED** [review]
I'm happy with this for Copter.  I imagine that @peterbarker might prefer that we add an accessor to Mode called something like "virtual bool allow_gndeffect_comp() const { return false; }" but that could possibly be done as a follow-up.

**Comment by priseborough** [comment]
I've created fixes to prevent the possibility of the way the takeoff  baro limiting is handled causing problems in the future. Takeoff now uses the same dead zone method as landing and the dead zone is now tuneable because the size of the baro error varies a lot between platforms.

See  https://github.com/priseborough/ardupilot/commit/dc19306e240a6f68189ca09f733badaaebd221d5 and https://github.com/priseborough/ardupilot/commit/9a030d7ea5a780e5777422bfa13347f1d1d63a92 in  https://github.com/priseborough/ardupilot/tree/pr/fix-ground-effect-compensation

**Comment by tridge** [comment]
> Takeoff now uses the same dead zone method as landing and the dead zone is now tuneable because the size of the baro error varies a lot between platforms.

that change also means we now apply that deadzone for fixed wing takeoff, due to the delta-velocity 1g accel trigger in EKF3 for setting takeoff. I don't think we should be applying the deadzone for hand launch takeoff, as humans are less than 4m tall

**Comment by priseborough** [comment]
> > 
> that change also means we now apply that deadzone for fixed wing takeoff, due to the delta-velocity 1g accel trigger in EKF3 for setting takeoff. I don't think we should be applying the deadzone for hand launch takeoff, as humans are less than 4m tall

This is unlikely to be an issue because the dead-zone starts at 0.5m, is applied to the innovation, not the measurement and the GPS vertical velocity constrains the rate of drift. Also for many FW platforms, the baro actually gains a positive height error during the throw due to  airflow induced reduction of static pressure inside the fuselage. However the simple way to avoid this potential issue altogether is to make the application of the baro ground effect compensation conditional on not operating in a zero sideslip assumption. See https://github.com/priseborough/ardupilot/commit/ab67d633bc5b9acaded5b9fc50a18ba43cd7246c

**Comment by tridge** [comment]
> This is unlikely to be an issue because the dead-zone starts at 0.5m, is applied to the innovation, not the measurement and the GPS vertical velocity constrains the rate of drift. Also for many FW platforms, the baro actually gains a positive height error during the throw due to airflow induced reduction of static pressure inside the fuselage.

ok, I'm convinced, thanks!
I've applied your changes to this PR, leaving it enabled for fixed wing
do we want to change EKF2 at this stage? It has the old MAX() method

**Comment by tridge** [comment]
@priseborough the MAX() method is actually in a 2nd place in EKF3:
https://github.com/peterbarker/ardupilot/blob/pr%2Ffix-ground-effect-compensation/libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp#L1187
should we remove that?

**Comment by priseborough** [comment]
> @priseborough the MAX() method is actually in a 2nd place in EKF3:
> https://github.com/peterbarker/ardupilot/blob/pr%2Ffix-ground-effect-compensation/libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp#L1187
> should we remove that?

Yes - https://github.com/priseborough/ardupilot/commit/6b327bf88ed6a0bad75f6e4b07befa1127838994

**Comment by tridge** [comment]
> Yes - [priseborough@6b327bf](https://github.com/priseborough/ardupilot/commit/6b327bf88ed6a0bad75f6e4b07befa1127838994)

thanks Paul, applied

**Comment by tridge** [comment]
@rmackay9 the last of the issues is now fixed, just need testing and merge

**Comment by rmackay9** [comment]
@tridge, @priseborough,

I was hoping to test this today but didn't quite get there.  I'm sure I'll test it tomorrow though.

**Comment by rmackay9** [comment]
I've just run a short test using my regular IRIS (minus the legs) with a simple takeoff + land mission and it seemed to perform well.
image

Logs: https://www.dropbox.com/s/p42ce1i2a1c00le/ekf-gndeff-02Jun2021.bin?dl=0

**Review by priseborough — APPROVED** [review]
Log shared by @rmackay9 shows expected behaviour

**Comment by rmackay9** [comment]
Merged, thanks!
