### PR TITLE
AP_MSP: fix DJI FPV temperature and RPM

### LINKED ISSUE #17623: Arduplane latest 4.1 BLHTEMP does not work in DJI MSP OSD
#### Issue details
 BLHTEMP does not work in DJI MSP OSD

#### Version
Arduplane 4.1 
From 2021-05-12 it is not displayed on OSD.
Before this date, the temperature was displayed, but it did not change.

#### Platform
[ X] Plane
#### Airframe type
Flying wing

#### Hardware type
Matek H743 slim

ESC telemetry works, temperature, voltage, current and RPM are recorded in log normally.

image

### PR DESCRIPTION
**Pull request by shellixyz**
Version 1.00.06 (latest at the time this PR is submitted) of DJI firmware is not using the standard MSP_ESC_SENSOR_DATA. In fact no version is AFAIK.

With MSP_OPTIONS = 2 (DJI Workarounds) the temperature and RPM are displayed correctly. Since only the one temperature and one RPM can be displayed what is sent to the Air Unit/OSD is the maximum temperature and average RPM across all ESCs.

Closes #17623

### CODE REVIEW

File: libraries/AP_MSP/AP_MSP_Telem_DJI.cpp [hunk 1]
```diff
@@ -104,4 +104,31 @@ MSPCommandResult AP_MSP_Telem_DJI::msp_process_out_fc_variant(sbuf_t *dst)
...
+    if (AP::msp()->_options & AP_MSP::OPTION_TELEMETRY_DJI_WORKAROUNDS) {
+        AP_ESC_Telem& telem = AP::esc_telem();
+        if (telem.get_last_telem_data_ms(0)) {
+            int16_t max_temperature = INT16_MIN;
+            float rpm_acc = 0;
+            const uint8_t num_motors = telem.get_num_active_escs();
+            for (uint8_t i = 0; i < num_motors; i++) {
+                int16_t temp = 0;
+                float rpm = 0.0f;
+                telem.get_rpm(i, rpm);
```
Comment (andyp1per) [inline libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:119]: There is already a function to compute the average rpm - you should use it. You are not checking the return value here, the rpm returned could be out of range

**Review by andyp1per — CHANGES_REQUESTED** [review]

File: libraries/AP_MSP/AP_MSP_Telem_DJI.cpp (hunk 1 above)
Comment (shellixyz) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:119]: I assumed the code in `AP_MSP_Telem_Backend.cpp` was good. This part is just a copy. But I'm going to take a look

Comment (shellixyz) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:119]: There is `get_average_motor_frequency_hz()` but I don't see a method to get the average RPM

Comment (andyp1per) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:119]: x60?

Comment (shellixyz) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:119]: I don't see any problem not checking the return value of `get_rpm()` or `get_temperature()` since the value of the reference won't change in case where it is not possible to get a value and it returns false. It is not like we could make the OSD element blink with DJI FPV to indicate a problem.

Perhaps you will like this new version better anyway

Comment (shellixyz) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp]: > x60?

Yeah ok but I don't like that much. Using RPM to compute the frequency then using the frequency to compute back the RPM

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp [hunk 2]
```diff
@@ -130,6 +137,20 @@ bool AP_ESC_Telem::get_temperature(uint8_t esc_index, int16_t& temp) const
...
+{
+    uint8_t valid_escs = 0;
+
+    for (uint8_t i = 0; i < ESC_TELEM_MAX_ESCS; i++) {
+        if (get_temperature(i, temp)) {
+            valid_escs++;
+        }
+    }
+
+    return !!valid_escs;
```
Comment (andyp1per) [inline libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:151]: I'm assuming this is a typo. Better to compare to 0.

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp [hunk 3]
```diff
@@ -34,25 +34,32 @@ AP_ESC_Telem::AP_ESC_Telem()
...
     }
 
-    return motor_freq;
+    return rpm_avg;
+}
+
+// return the average motor frequency in Hz for dynamic filtering
+float AP_ESC_Telem::get_average_motor_frequency_hz() const
+{
+    return get_average_rpm() / 60.0;
```
Comment (andyp1per) [inline libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:62]: Probably would be better if this was inlined, but I doubt it makes that much difference

**Review by andyp1per — CHANGES_REQUESTED** [review]
Just need to fix the typo

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp (hunk 2 above)
Comment (shellixyz) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:151]: Not a typo. `!!x` is commonly used to convert an integer to boolean, it is equivalent to `x != 0`

Comment (andyp1per) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:151]: Ok I stand corrected!

**Review by andyp1per — APPROVED** [review]

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp (hunk 3 above)
Comment (shellixyz) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp]: Done :+1:

File: libraries/AP_MSP/AP_MSP_Telem_DJI.cpp [hunk 4]
```diff
@@ -104,4 +104,20 @@ MSPCommandResult AP_MSP_Telem_DJI::msp_process_out_fc_variant(sbuf_t *dst)
     return MSP_RESULT_ACK;
 }
 
+MSPCommandResult AP_MSP_Telem_DJI::msp_process_out_esc_sensor_data(sbuf_t *dst)
+{
+#if HAL_WITH_ESC_TELEM
+    if (AP::msp()->_options & AP_MSP::OPTION_TELEMETRY_DJI_WORKAROUNDS) {
```
Comment (tridge) [inline libraries/AP_MSP/AP_MSP_Telem_DJI.cpp:110]: need to check for null from AP::msp()

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp [hunk 5]
```diff
@@ -130,6 +131,20 @@ bool AP_ESC_Telem::get_temperature(uint8_t esc_index, int16_t& temp) const
...
+{
+    uint8_t valid_escs = 0;
+
+    for (uint8_t i = 0; i < ESC_TELEM_MAX_ESCS; i++) {
+        if (get_temperature(i, temp)) {
+            valid_escs++;
+        }
+    }
+
+    return !!valid_escs;
```
Comment (tridge) [inline libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:145]: add a comment, as some people won't understand it

**Review by tridge — CHANGES_REQUESTED** [review]

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp [hunk 6]
```diff
@@ -130,6 +131,20 @@ bool AP_ESC_Telem::get_temperature(uint8_t esc_index, int16_t& temp) const
     return true;
 }
 
+// get the highest ESC temperature in centi-degrees if available, returns true on success
+bool AP_ESC_Telem::get_highest_temperature(int16_t& temp) const
+{
+    uint8_t valid_escs = 0;
+
+    for (uint8_t i = 0; i < ESC_TELEM_MAX_ESCS; i++) {
+        if (get_temperature(i, temp)) {
```
Comment (peterbarker) [inline libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:140]: In what way is that getting the highest temperature?

File: libraries/AP_MSP/AP_MSP_Telem_DJI.cpp (hunk 4 above)
Comment (shellixyz) [reply libraries/AP_MSP/AP_MSP_Telem_DJI.cpp]: ok, done

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp (hunk 5 above)
Comment (shellixyz) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp]: ok, done

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp (hunk 6 above)
Comment (shellixyz) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp]: You're right it is not, something has been lost in translation. Fixed

**Comment by hyperion11** [comment]
looking forward in 4.1 beta 3 :)

**Comment by yaapu** [comment]
@shellixyz in the meantime I added a method that you could use :-)
https://github.com/ArduPilot/ardupilot/blob/7ca0aa7c94bebf109c0bea0b24bd718f2566ec4e/libraries/AP_ESC_Telem/AP_ESC_Telem.cpp#L67

you could declare

```
float AP_ESC_Telem::get_average_rpm() const
{
 return get_average_motor_rpm(0xFFFFFFFF);
}
```

**Comment by shellixyz** [comment]
TBH I'm tired of maintaining PRs for months when this should have been merged right away when I made the requested changes. On top of it this PR is needed to fix the ESC telemetry on analog OSD so I have been waiting for this to be merged to propose the PR to fix that.

So now there is a new conflict and the proposed solution is to use a method which is instead of just taking the average of the RPM like I proposed does a bunch of useless calculation by first calculating the motor frequency then converting it back to RPM. Doesn't make any sense.

Now I'm just maintaining my own branch and that's gonna be it.

**Comment by andyp1per** [comment]
@shellixyz I've added devcall topic for this evening - if you can get it rebased it might get merged.

**Comment by yaapu** [comment]
@shellixyz didn't mean to cause any troubles especially since your PR is fixing something I originally wrote.
The method that "does a bunch of useless calculation by first calculating the motor frequency then converting it back to RPM" is mine as well, instead of duplicating Andy's hz code to calculate rpm (which just like you was my first proposal) Andy suggested to use Hz as a base for rpm since the error would have negligible.
I think we should really value everyone's contribution so thanks for the PR, as for the frustation of seeing our PRs being forgotten...well we've all been there

**Comment by shellixyz** [comment]
Sorry didn't mean to be harsh but all it did was to give me more work for something which has been ready for a long time. I'm working on rebasing this now. The problem is not the floating point error that could result but dividing all the RPMs by 60 to get the frequency then multiplying the average by 60. In embedded systems with limited CPU resouce it doesn't make any sense to me when it is possible to just have a method averaging the RPMs, result which is used by the OSD code then use also this result to then compute the frequency. Doesn't take more cycles for calculating the frequency and takes less for calculating the average RPM.

**Comment by shellixyz** [comment]
Should be good to go

**Review by tridge — APPROVED** [review]

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp [hunk 7]
```diff
@@ -156,6 +145,22 @@ bool AP_ESC_Telem::get_motor_temperature(uint8_t esc_index, int16_t& temp) const
...
+
+    for (uint8_t i = 0; i < ESC_TELEM_MAX_ESCS; i++) {
+        int16_t temp_temp;
+        if (get_motor_temperature(i, temp_temp)) {
+            temp = MAX(temp, temp_temp);
+            valid_escs++;
+        }
+    }
+
+    return !!valid_escs; // return true if valid_escs > 0
```
Comment (peterbarker) [inline libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:161]:
```suggestion
    return valid_escs > 0;
```

If it needs a comment.... :-)

**Review by peterbarker — APPROVED** [review]

File: libraries/AP_ESC_Telem/AP_ESC_Telem.cpp (hunk 7 above)
Comment (shellixyz) [reply libraries/AP_ESC_Telem/AP_ESC_Telem.cpp:161]: So first you ask me to add a comment then you ask me to change it because it needed a comment. You guys... :rofl:

**Comment by tridge** [comment]
@shellixyz apologies for the delay with this one

**Comment by yaapu** [comment]
@shellixyz thanks for the fix!
