### PR TITLE
EKF: Fixed position error on GPS primary switch

### LINKED ISSUE #13384: GPS switch causes position change
If two GPS modules are placed a considerable distance apart on a hovering vehicle with correct sensor positioning information in parameters and you switch which GPS is active then there should be zero impact on the vehicle.
Tests in SITL show this is not the case. With this PR #13383  and these settings:
SIM_GPS_POS_Y -5
SIM_GPS2_POS_Y 5
GPS_POS1_Y -5
GPS_POS2_Y 5
SIM_GPS2_ENABLE 1
GPS_TYPE2 1

then hover in SITL copter and switch GPS_AUTO_SWITCH between 0 and 3. The copter moves position quite a lot. This looks like a bug

### PR DESCRIPTION
**Pull request by tridge**
This fixes #13384 
This bug particularly affects moving baseline GPS setups as they have significant separation between the GPS modules and will switch between modules when they gain/lose GPS yaw

### CODE REVIEW

File: libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp [hunk 1]
```diff
@@ -240,6 +246,28 @@ bool NavEKF3_core::resetHeightDatum(void)
     return true;
 }
 
+/*
+  correct GPS data for position offset of antenna phase centre relative to the IMU
+ */
+void NavEKF3_core::CorrectGPSForAntennaOffset(gps_elements &gps_data)
```
Comment (varunv997) [inline libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp]: [Redundant Code] Hi. Can this method be moved to NavEKF_core_common.h/.cpp, the common parent class? Sorry if I misunderstand, the same piece of code has been used both in  NavEKF3_core and NavEKF2_core.

Comment (tridge) [reply libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp]: gps_elements is defined as a local structure in each class, so we'd have to move that up as well. We could do that, but Paul may prefer to keep things more separated

Comment (varunv997) [reply libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp]: In that case, lets go ahead. :D

**Comment by rmackay9** [comment]
This PR very likely resolves this issue: https://github.com/ArduPilot/ardupilot/issues/13503

**Comment by rmackay9** [comment]
this is included in Copter-4.0.4-rc1
