### PR TITLE
AP_Mission: Sanity check for NaN's and infinities

### LINKED ISSUE #2515: ArduPilot should test for valid input on takeoff
ArduPilot does not check for NaN or Inf (infinity) values for the takeoff parameter command, and could potentially fly to a random location if such input was received (according to @billbonney ). Testing using dronekit shows that float("nan") is denied by arducopter but float("inf")) crashes arducopter or SITL.

Dronekit now checks against the invalid input (i.e. programmatic errors https://github.com/diydrones/dronekit-python/issues/174) and we think ArduCopter probably should too.

Further, we think that it might be useful to have a parameter defining a reasonable maximum value if the Geofence altitude is not set.

### PR DESCRIPTION
**Pull request by WickedShell**
Add's sanity checks for NaN's/Infinites that are not expected on a command, fixes possible FPE faults from bad GCS behaviour, and closes #2515

### CODE REVIEW

**Comment by magicrub** [comment]
LGTM. However, are these NAN exceptions ok for all vehicle types?

**Comment by WickedShell** [comment]
@magicrub Yeah. The reality is actually that every NaN that is acceptable we don't do anything with anyways, but they are at least fields that a GCS can/should be setting to NaN. (It's not worth trying to enforce the NaN requirement though).

**Comment by magicrub** [comment]
so GCSs that are currently sending NaNs that we were allowing, but ignoring because they're not part of the mission, will not get a reject NAK msg?

I'm ok with that. Best to double-check with @meee1 before we merge though.

**Comment by WickedShell** [comment]
Correct. If the NaN is part of the actual spec it's still accepted. If it's not part of the spec then it's going to be NAK'd with this. I wasn't to worried about MP because to the best of my knowledge you can't type a NaN into a text box, and I don't think it applies any automatic transformations of outgoing waypoints depending upon the type.

File: libraries/AP_Mission/AP_Mission.cpp [hunk 1]
```diff
@@ -530,6 +530,48 @@ void AP_Mission::write_home_to_storage()
...
+            nan_mask = ~(1 << 3); // param 4 can be nan
+            break;
+        case MAV_CMD_NAV_TAKEOFF:
+            nan_mask = ~(1 << 3); // param 4 can be nan
+            break;
+        case MAV_CMD_NAV_VTOL_TAKEOFF:
+            nan_mask = ~(1 << 3); // param 4 can be nan
+            break;
+        case MAV_CMD_NAV_VTOL_LAND:
+            nan_mask = ~((1 << 2) || (1 << 3)); // param 3 and 4 can be nan
```
Comment (OXINARF) [inline libraries/AP_Mission/AP_Mission.cpp]: This should be a `|`, not an `||`. I'll make a commit to fix it.

Comment (magicrub) [reply libraries/AP_Mission/AP_Mission.cpp]: good catch!
