### PR TITLE
Compass: report reason when mag calibration fails

### LINKED ISSUE #13257: ROVER?: Compass Calibration silently fails if enabled compass is not present
### Bug report

**Issue details**
When using only a UAVCAN compass (USE_COMPASS 0, USE_COMPASS2 0, USE_COMPASS3 1, COMPASS_PRIMARY 3), and the compass is not detected, Mag Calibration does not start, but there is no indication anything failed.

**Version**
ROVER 4.0.0 release 

**Platform**
Not sure if this is only on Rover, might be on other platforms too.
[  ] All
[  ] AntennaTracker
[  ? ] Copter
[ ? ] Plane
[ X ] Rover
[ ? ] Submarine

**Hardware type**
Tested using Here2 on UAVCAN with CubeBlack and CubeOrange

### PR DESCRIPTION
**Pull request by TharakaUJ**
When MAV_CMD_DO_START_MAG_CAL fails because no compasses are available for calibration, the command currently returns MAV_RESULT_FAILED but does not send a message to the GCS.

Send a STATUSTEXT message so the user receives feedback instead of a silent failure.

## Summary

(in the commit message above)

## Testing (more checks increases chance of being merged)

- [x] Checked by a human programmer
- [x] Tested in SITL
- [ ] Tested on hardware
- [ ] Logs attached
- [x] Logs available on request
- [ ] Autotest included

## Description

Fixes #13257

### CODE REVIEW

File: libraries/AP_Compass/AP_Compass_Calibration.cpp [hunk 1]
```diff
@@ -399,10 +399,12 @@ MAV_RESULT Compass::handle_mag_cal_command(const mavlink_command_int_t &packet)
         if (mag_mask == 0) { // 0 means all
             _reset_compass_id();
             if (!start_calibration_all(retry, autosave, delay, autoreboot)) {
+                GCS_SEND_TEXT(MAV_SEVERITY_ERROR, "Compass calibration failed: no compasses started");
```
Comment (peterbarker) [inline libraries/AP_Compass/AP_Compass_Calibration.cpp]: Is this accurate?

File: libraries/AP_Compass/AP_Compass_Calibration.cpp [hunk 2]
```diff
@@ -399,10 +399,12 @@ MAV_RESULT Compass::handle_mag_cal_command(const mavlink_command_int_t &packet)
...
                 result = MAV_RESULT_FAILED;
             }
         } else {
             if (!_start_calibration_mask(mag_mask, retry, autosave, delay, autoreboot)) {
+                GCS_SEND_TEXT(MAV_SEVERITY_ERROR, "Compass calibration failed: no compasses started");
```
Comment (peterbarker) [inline libraries/AP_Compass/AP_Compass_Calibration.cpp]: Is this accurate?

File: libraries/AP_Compass/AP_Compass_Calibration.cpp (hunk 1 above)
Comment (rmackay9) [reply libraries/AP_Compass/AP_Compass_Calibration.cpp]: Txs for this.  look at the start_calibration_all() and _start_calibration_mask() functions which call _start_calibration() it seems that there could be various reasons it could fail:

1. no compasses are enabled
2. there are no healthy compasses

Depending upon how kind we want to be we could add checks and early returns higher in the Compass::handle_mag_cal_command() function or we could change the error message that's been added here to something simpler.  Like "Compass calibration failed to start".  It doesn't give a reason why but it's perhaps better than a silent failure

BTW, @peterbarker, if we go for the vague error message option, does it result in lower flash if we just have a single line at the end?  something like this?

```
if (result == MAV_RESULT_FAILED) {
    GCS_SEND_TEXT(MAV_SEVERITY_NOTICE, "Compass calibration failed to start");
}
```

I think it doesn't matter if we have two separate messages or just one because the compiler will just handle it for us

**Comment by TharakaUJ** [comment]
> Explain how you tested this change.

Tested in SITL (Rover) using both MAVProxy and QGroundControl.

Steps:

1. Start SITL:

```
./Tools/autotest/sim_vehicle.py -v Rover
```

2. In MAVProxy:

```
magcal start
```

Calibration starts normally.

3. Disable compass system:

```
param set COMPASS_ENABLE 0
```

4. Start calibration again:

```
magcal start
```

Before this change:

```
Got COMMAND_ACK: DO_START_MAG_CAL: FAILED
```

(no explanatory message)

After this change:

```
Got COMMAND_ACK: DO_START_MAG_CAL: FAILED
AP: Compass calibration failed: no compasses started
```

I also verified the same behavior in QGroundControl where the error message now appears in the vehicle messages panel.

File: libraries/AP_Compass/AP_Compass_Calibration.cpp (hunk 1 above)
Comment (TharakaUJ) [reply libraries/AP_Compass/AP_Compass_Calibration.cpp]: Thanks for the review and suggestions.

I see that calibration can fail for several reasons, so the message I added is too specific. I'll update the patch to use a more generic message like:

"Compass calibration failed to start"

and send a single message with `MAV_SEVERITY_NOTICE` when `result == MAV_RESULT_FAILED`.

Comment (TharakaUJ) [reply libraries/AP_Compass/AP_Compass_Calibration.cpp]: One possible improvement I considered was adding an early check like:

if (!available()) {
    GCS_SEND_TEXT(MAV_SEVERITY_ERROR, "Compass calibration requires compass to be enabled");
    result = MAV_RESULT_FAILED;
    break;
}

but since the lower-level calibration functions already return failure in this case, I wasn't sure if adding this check would be preferred or unnecessary.

**Comment by TharakaUJ** [comment]
Updated the patch to use a single generic message ("Compass calibration failed to start") with MAV_SEVERITY_NOTICE when calibration cannot start.

tested with QGC and in the SITL terminal got:
```
Got COMMAND_ACK: DO_START_MAG_CAL: FAILED
AP: Compass calibration failed to start
```
and same message was logged in QGC as well.

**Review by rmackay9 — APPROVED** [review]

File: libraries/AP_Compass/AP_Compass_Calibration.cpp [hunk 3]
```diff
@@ -407,6 +407,10 @@ MAV_RESULT Compass::handle_mag_cal_command(const mavlink_command_int_t &packet)
             }
         }
 
+        if (result == MAV_RESULT_FAILED) {
```
Comment (peterbarker) [inline libraries/AP_Compass/AP_Compass_Calibration.cpp]:
```suggestion
        if (result != MAV_RESULT_ACCEPTED) {
```

Less likely to break in the future

**Review by peterbarker — CHANGES_REQUESTED** [review]

File: libraries/AP_Compass/AP_Compass_Calibration.cpp (hunk 3 above)
Comment (TharakaUJ) [reply libraries/AP_Compass/AP_Compass_Calibration.cpp]: I see, that makes sense. Thank you!

**Review by peterbarker — APPROVED** [review]

**Comment by TharakaUJ** [comment]
Thanks for the reviews and guidance!
