### PR TITLE
AP_Airspeed: fixed timing errors in MS5525 driver

### LINKED ISSUE #7188: 5525 airspeed i2c noise
We need a way to filter noise on the MS5525 airspeed sensor. On the 4425 we can use double reads to detect errors. On the MS5525 we can't do that, as a 2nd read will always give zero. This is a log of a flight leading to a stall and crash due to extreme i2c noise.
ms5525-airspeed-noise

Log is here: http://uav.tridgell.net/DaleRogers/00000021.BIN

### PR DESCRIPTION
**Pull request by tridge**
this fixes #7188, where we could read from the MS5525 sensor too
soon after requesting data and the result coming back would be garbage
I could reproduce the issue by deliberately reading from the sensor too fast

### CODE REVIEW

File: libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp [hunk 1]
```diff
@@ -226,30 +227,54 @@ void AP_Airspeed_MS5525::calculate(void)
...
+    if (adc_val == 0) {
+        // we have either done a read too soon after sending the
+        // request or we have tried to read the same sample twice. We
+        // re-send the command now as we don't know what state the
+        // sensor is in, and we do want to trigger it sending a value,
+        // which we will discard
+        if (dev->transfer(&cmd_sent, 1, nullptr, 0)) {
+            command_send_us = AP_HAL::micros();
+        }
+        // when we get adc_val == 0 then then both the current value and
```
Comment (OXINARF) [inline libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp]: then then...

This sentence is being hard to be correct 😛

**Comment by DroneExplorer** [comment]
Hi Guys,

Will this be integrated in the 3.8.4 release, or can I change it right now ?

Sorry for the noob question,
Regards,
Hamza

**Comment by magicrub** [comment]
this is a good candidate for 3.8.4

**Comment by tridge** [comment]
yes, this will be in 3.8.4. I did a test flight of this on top of 3.8.3 today and it went well
