### PR TITLE
libraries: fix LTE_MCCMNC documentation metadata

### LINKED ISSUE #31332: Parameter LTE_MCCMNC has invalid metadata
## Bug report

**Issue details**
During to autopilot connection got this:

2025-10-19 20:54:58,030 - WARNING - Could not convert values to int or float for LTE_MCCMNC
2025-10-19 20:54:58,031 - WARNING - Parameter LTE_MCCMNC has invalid metadata. Please file a bug at https://github.com/ArduPilot/ardupilot/issues

**Version**
4.6.2

**Platform**
[  ] All
[  ] AntennaTracker
[x  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad

**Hardware type**
Matek H743

**Logs**
2025-10-19 20:54:58,030 - WARNING - Could not convert values to int or float for LTE_MCCMNC
2025-10-19 20:54:58,031 - WARNING - Parameter LTE_MCCMNC has invalid metadata. Please file a bug at https://github.com/ArduPilot/ardupilot/issues

### PR DESCRIPTION
**Pull request by amilcarlucas**
fixes #31332

### CODE REVIEW

File: libraries/AP_Scripting/drivers/LTE_modem.lua [hunk 1]
```diff
@@ -145,7 +145,7 @@ local LTE_IBAUD       = bind_add_param('IBAUD', 13, 115200)
     // @Param: LTE_MCCMNC
     // @DisplayName: LTE operator selection
     // @Description: This allows selection of network operator
-    // @Values: -1:NoChange,0:Default,AU-Telstra:50501,AU-Optus:50502,AU-Vodaphone:50503
+    // @values: -1:NoChange,0:Default,50501:AU-Telstra,50502:AU-Optus,50503:AU-Vodafone
```
Comment (tpwrules) [inline libraries/AP_Scripting/drivers/LTE_modem.lua]:
```suggestion
    // @Values: -1:NoChange,0:Default,50501:AU-Telstra,50502:AU-Optus,50503:AU-Vodafone
```

Comment (IamPete1) [reply libraries/AP_Scripting/drivers/LTE_modem.lua]: I wonder if this is why the existing documentation check missed it.

Comment (tpwrules) [reply libraries/AP_Scripting/drivers/LTE_modem.lua]: The requested change here is to fix an error just introduced by this PR. I think there is probably still a problem with the docs check.

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Whoops.  We all missed the commit message wasn't right.  I've corrected it.

**Comment by amilcarlucas** [comment]
CI has passed, commit message is fixed. This can go in.
