### PR TITLE
HAL_ChibiOS: fixed handling of 16bit timer wrap

### LINKED ISSUE #12948: Plane: Flight timer on OSD (MAX7456) displays random digits after some time
After 67:07 minutes of flight the flight timer duration on the OSD started to show random values , using lot of space and covering other symbols as you can see from the current screenshot:

image

Video showing the issue:

[2019-12-02 10.38.19.mp4.zip](https://github.com/ArduPilot/ardupilot/files/3910507/2019-12-02.10.38.19.mp4.zip)

**Version**
Running Master at fba5732292 compiled on OSX using the suggested compiler from brew.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
Matek F405 STD (ChibiOS) 

**Logs**
Have been sent directly to @tridge for privacy reasons.

### PR DESCRIPTION
**Pull request by tridge**
this fixes #12948
This is a critical fix for MatekF765 and MatekF405, which use 16 bit timers
This adds a common system_time_u32_us() so 16 bit and 32 bit systems have identical behaviour

### CODE REVIEW

File: libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c [hunk 1]
```diff
@@ -20,50 +20,49 @@
...
+    return timer_base_us32;
 }
-
 #elif CH_CFG_ST_RESOLUTION == 32
-static uint32_t get_systime_us32(void)
+static uint32_t system_time_u32_us(void)
 {
-    systime_t now = chVTGetSystemTimeX();
-#if CH_CFG_ST_FREQUENCY != 1000000
+    uint32_t now = chVTGetSystemTimeX();
```
Comment (peterbarker) [inline libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c]: Why's this changed from `systime_t`?  The static assert down below seems to guarantee this was OK.

Comment (tridge) [reply libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c]: fixed

**Comment by rmackay9** [comment]
this has been added to Copter-4.0.0-rc3
