### PR TITLE
AP_Mount: fix scripting backend and remove unnecessary state variables

### LINKED ISSUE #31535: AP_Mount_Scripting location_is_valid method broken
## Bug report

**Issue details**

https://github.com/ArduPilot/ardupilot/pull/23837 removed setting of `target_loc_valid` to anything other than true from the AP_Mount_Scripting backend.

The Lua binding is the only thing that makes use of this state.

We should also probably not have target_loc_valid at all - the location can be set to all-zeroes to flag it as invalid (dependent variables that don't exist can't get stale).  The same is true of `_roi_target_set` and `_target_sysid_location_set` (which we should probably use in place of target_loc_valid; i.e. switch on the current mount mode and return based on the presumably-set-correctly variables.

**Version**
master

**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
all

**Hardware type**
inspection

**Logs**

n/a

### PR DESCRIPTION
**Pull request by neo-0007**
The `target_loc` and its validity flag can be removed since it's not set anywhere and only used by the `get_location_target` that sets the target location for which we can use the base class variables that already stores the location for specific modes and also their flags.

The `_roi_target_set` and `_target_sysid_location_set` can also be removed since we can check the validity using `initialized()` method and clear by setting all values as zero. 

Also should i remove the underscore from the variables since they are moved to protected and  not private variables anymore ? 

Should fix #31535

### CODE REVIEW

**Comment by neo-0007** [comment]
This approach may not what is wanted and also autotest is required as mentioned by @peterbarker , so marking this as draft till its reviewed.

File: libraries/AP_Mount/AP_Mount_Scripting.cpp [hunk 1]
```diff
@@ -94,9 +90,34 @@ bool AP_Mount_Scripting::healthy() const
...
 bool AP_Mount_Scripting::get_location_target(Location &_target_loc)
 {
-    if (target_loc_valid) {
-        _target_loc = target_loc;
-        return true;
+    switch (get_mode()) {
+        case MAV_MOUNT_MODE_GPS_POINT:
+            if (_roi_target_set) {
+                _target_loc = _roi_target;
+                return true;
```
Comment (peterbarker) [inline libraries/AP_Mount/AP_Mount_Scripting.cpp]:
```suggestion
                return _target_loc.initialised();
```

etc

**Comment by peterbarker** [comment]
> The `target_loc` and its validity flag can be removed since it's not set anywhere and only used by the `get_location_target` that sets the target location for which we can use the base class variables that already stores the location for specific modes and also their flags.

I wonder why they were historically needed...
 
> The `_roi_target_set` and `_target_sysid_location_set` can also be removed since we can check the validity using `initialized()` method and clear by setting all values as zero.

... so yeah, we should actually use _initialised(), right? :-)

> Also should i remove the underscore from the variables since they are moved to protected and not private variables anymore ?

No - pointless churn.  But our modern pattern is "don't use underscores on member variables".

File: libraries/AP_Mount/AP_Mount_Scripting.cpp (hunk 1 above)
Comment (neo-0007) [reply libraries/AP_Mount/AP_Mount_Scripting.cpp]: Updated, thanks !

**Comment by neo-0007** [comment]
If any more changes required  i am happy to make them, 
For the autotest i am learning how write one myself but any suggestions would be very helpful !

**Comment by peterbarker** [comment]
> If any more changes required i am happy to make them, For the autotest i am learning how write one myself but any suggestions would be very helpful !

This looks solid.

Does need that autotest, and descriptions of whatever other tests you've made.

Best idea is to steal as much autotest code from other places as you can.  General shape will be to install the example or applet lua script, configure a mount and then make sure the script is getting the location where you're pointing the gimbal.

**Comment by neo-0007** [comment]
Thanks @peterbarker ,

The scripting apis i updated were not used by any existing scripts in applets or in examples folder , So i created a lua script 
```lua
-- Test mount scripting backend
local UPDATE_MS = 100

function update()
    -- Keep mount healthy
    mount:set_attitude_euler(0, 0, -30, 0)
    
    -- Test get_location_target every 2 seconds
    if millis() % 2000 < 100 then
        local mode = mount:get_mode(0)
        local target = mount:get_location_target(0)
        
        if target then
            gcs:send_text(6, string.format("Mode %d: %.6f,%.6f", 
                mode, target:lat()/1e7, target:lng()/1e7))
        else
            gcs:send_text(6, string.format("Mode %d: No target", mode))
        end
    end
    
    return update, UPDATE_MS
end

return update()
```
*The above script was written with the help of AI*

and ran it using SITL with scripting enabled :
image

Here I tested the 2 modes that returns a valid location ROI_LOCATION  and Home Location and they works just fine.

**Comment by peterbarker** [comment]
> Here I tested the 2 modes that returns a valid location ROI_LOCATION and Home Location and they works just fine.

Excellent!

Make sure you commit that script and push it up as an example.  It sometimes takes a bit to get scripts to pass our CI checks, so earlier is better.

Let me know if you need help with the autotest.

**Comment by neo-0007** [comment]
I tried writing a autotest by looking at other tests , but the test fails every time , I manually tested all the steps in SITL many times and it works as intended :
Here are the steps:
```
Launch SITL

SET PARAMETERS: 
param set SCR_ENABLE 1
param set MNT1_TYPE 9

reboot

Copy the script into sitl_running_dir/scripts/

On restart, SITL prints repeatedly:
AP: Mode 3: No target

RETRACT MODE:
long DO_MOUNT_CONTROL 0 0 0 0 0 0 0
AP: Mode 0: No target

NEUTRAL MODE:
long DO_MOUNT_CONTROL 0 0 0 0 0 0 1
AP: Mode 1: No target

MAVLINK_TARGETING Mode:
long DO_MOUNT_CONTROL 0 0 0 0 0 0 2
AP: Mode 2: No target

Test RC_TARGETING Mode:
long DO_MOUNT_CONTROL 0 0 0 0 0 0 3
AP: Mode 3: No target

Set ROI_LOCATION
long MAV_CMD_DO_SET_ROI_LOCATION 1 0 0 0 -35.363150 149.165320 580
Automatically switches to GPS_POINT mode  and prints the intended :
AP: Mode 4: -35.363150 149.165320 580

Switch to HOME_LOCATION Mode:
long DO_MOUNT_CONTROL 0 0 0 0 0 0 6
Prints the intended :
AP: Mode 6: <home_lat> <home_lon>

Send SYSID target:
long MAV_CMD_DO_SET_ROI_SYSID 1 1
For the SYSID target ,Target will be empty because SITL has no target-vehicle.
AP: Mode 5: No target
```



@peterbarker , It would be a great if i can get some help with the autotest , Thanks !

File: Tools/autotest/arducopter.py [hunk 2]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
 
         self.context_pop()
         self.reboot_sitl()
+    
+    def ScriptMountAllModes(self):
+        '''test location from all mount modes using the scripting backend'''
+        self.context_push()
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]:
```suggestion
```

File: Tools/autotest/arducopter.py [hunk 3]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+        )
+        self.run_cmd(
+            mavutil.mavlink.MAV_CMD_DO_MOUNT_CONTROL,
+            p7=mavutil.mavlink.MAV_MOUNT_MODE_SYSID_TARGET
+        )
 
+        self.wait_statustext("Mode 5: No target", check_context=True)
+        
+        self.context_pop()
+        self.reboot_sitl()
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]:
```suggestion
```

File: Tools/autotest/arducopter.py [hunk 4]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+        )
+        self.wait_statustext(
+            rf"Mode 4:.*{expected_roi_lat}.*{expected_roi_lng}",
+            check_context=True, 
+            regex=True
+        )
+        
+        home_loc = self.mav.location()
+        expected_lat = "%.3f" % home_loc.lat
+        expected_lng = "%.3f" % home_loc.lng
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]: Good to have some variety.

But maybe choose one way or the other to truncate these values (see line 12756)

File: Tools/autotest/arducopter.py [hunk 5]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+        roi_lat = -35.363150
+        roi_lng = 149.165320
+        roi_alt = 580.0
+        
+         # Set ROI location
+        self.run_cmd(
+            mavutil.mavlink.MAV_CMD_DO_SET_ROI_LOCATION,
+            p5 = roi_lat,
+            p6 = roi_lng,
+            p7 = roi_alt
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]:
```suggestion
            p7 = roi_alt,
```

similarly elsewhere (always have a comma after the last item; when someone adds something later they only have to change one line)

File: Tools/autotest/arducopter.py [hunk 6]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+            mavutil.mavlink.MAV_CMD_DO_MOUNT_CONTROL,
+            p7=mavutil.mavlink.MAV_MOUNT_MODE_GPS_POINT
+        )
+        self.wait_statustext(
+            rf"Mode 4:.*{expected_roi_lat}.*{expected_roi_lng}",
+            check_context=True, 
+            regex=True
+        )
+        
+        home_loc = self.mav.location()
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]: This is not the home location.  There are methods to get that, 'though

File: Tools/autotest/arducopter.py [hunk 7]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+        self.wait_statustext(
+            rf"Mode 6:.*{expected_lat}.*{expected_lng}",
+            check_context=True,
+            regex=True
+        )
+        
+        self.run_cmd(
+            mavutil.mavlink.MAV_CMD_DO_SET_ROI_SYSID,
+            p1=1,
+            p2=1
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]: Comments on these lines as to what the magic numbers signify

File: Tools/autotest/arducopter.py [hunk 8]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+            rf"Mode 4:.*{expected_roi_lat}.*{expected_roi_lng}",
+            check_context=True, 
+            regex=True
+        )
+        
+        home_loc = self.mav.location()
+        expected_lat = "%.3f" % home_loc.lat
+        expected_lng = "%.3f" % home_loc.lng
+        
+        # Test HOME_LOCATION (mode 6)
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]:
```suggestion
        self.start_subtest("Test HOME_LOCATION (mode 6)")
```

similarly elsewhere

File: Tools/autotest/arducopter.py [hunk 9]
```diff
@@ -12691,7 +12691,112 @@ def ScriptMountPOI(self):
...
+            p6 = roi_lng,
+            p7 = roi_alt
+        )
+        expected_roi_lat = f"{roi_lat:.3f}"
+        expected_roi_lng = f"{roi_lng:.3f}"
+        
+        # Test GPS_POINT (mode 4)
+        self.run_cmd(
+            mavutil.mavlink.MAV_CMD_DO_MOUNT_CONTROL,
+            p7=mavutil.mavlink.MAV_MOUNT_MODE_GPS_POINT
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]: You are not passing in the location here

Further, you must pass in the lat/lng *1e7 and use `self.run_cmd_int` - we appear to have a bug in handling do_mount_control with gps-point in ArduPilot.

**Review by peterbarker — CHANGES_REQUESTED** [review]
Partial review only, just enough while I was tracking down the mode-4 issues

File: Tools/autotest/arducopter.py (hunk 6 above)
Comment (neo-0007) [reply Tools/autotest/arducopter.py]: tried using `home_position_as_mav_location` , it returned 0,0 so settled with `sitl_home()` , but it required some refactoring `lat, lng, alt, hdg = map(float, self.sitl_home().split(','))`

File: Tools/autotest/arducopter.py (hunk 7 above)
Comment (neo-0007) [reply Tools/autotest/arducopter.py]: I changed that to 
```python
        self.run_cmd(
            mavutil.mavlink.MAV_CMD_DO_SET_ROI_SYSID,
            p1=self.mav.source_system,
        )
```
which is self explainatory

File: Tools/autotest/arducopter.py (hunk 9 above)
Comment (neo-0007) [reply Tools/autotest/arducopter.py]: Thanks for this , this was causing the mode 4 to fail !

**Comment by neo-0007** [comment]
Updated as requested !
Now the test is passing and working as intended.
image

File: Tools/autotest/arducopter.py [hunk 10]
```diff
@@ -12692,6 +12692,101 @@ def ScriptMountPOI(self):
...
+            "MNT1_TYPE": 9,
+        })
+        self.reboot_sitl()
+
+        # install get-target-location-mount-backend.lua script
+        self.install_example_script_context('get-target-location-mount-backend.lua')
+        self.reboot_sitl()
+
+        self.wait_ready_to_arm()
+        self.arm_vehicle()
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]:
```suggestion
```

File: Tools/autotest/arducopter.py [hunk 11]
```diff
@@ -12692,6 +12692,101 @@ def ScriptMountPOI(self):
...
+
+        self.start_subtest("Test SYSID (mode 5)")
+        self.run_cmd(
+            mavutil.mavlink.MAV_CMD_DO_SET_ROI_SYSID,
+            p1=self.mav.source_system,
+        )
+        self.wait_statustext("Mode 5: No target", check_context=True)
+
+        self.start_subtest("Test HOME_LOCATION (mode 6)")
+        lat, lng, alt, hdg = map(float, self.sitl_home().split(','))
```
Comment (peterbarker) [inline Tools/autotest/arducopter.py]: This should probably `poll_home_position` instead - home might not be at sitl_home

**Review by peterbarker — APPROVED** [review]
LGTM

File: Tools/autotest/arducopter.py (hunk 11 above)
Comment (neo-0007) [reply Tools/autotest/arducopter.py]: Yes this would be the appropriate way , Thanks !

File: libraries/AP_Scripting/examples/get-target-location-mount-backend.lua [hunk 12]
```diff
@@ -0,0 +1,24 @@
...
+                mode, target:lat()/1e7, target:lng()/1e7))
+        else
+            gcs:send_text(6, string.format("Mode %d: No target", mode))
+        end
+    end
+    
+    return update, UPDATE_MS
+end
+
+return update()
```
Comment (IamPete1) [inline libraries/AP_Scripting/examples/get-target-location-mount-backend.lua]:
```suggestion
return update()

```

File: libraries/AP_Scripting/examples/get-target-location-mount-backend.lua [hunk 13]
```diff
@@ -0,0 +1,24 @@
+-- Test mount scripting backend
+local UPDATE_MS = 100
+
+function update()
+    -- Keep mount healthy
+    mount:set_attitude_euler(0, 0, -30, 0)
+    
+    -- Test get_location_target every 2 seconds
+    if millis() % 2000 < 100 then
```
Comment (IamPete1) [inline libraries/AP_Scripting/examples/get-target-location-mount-backend.lua]: This is a bit of a odd way to do this. Typically we would just calculate the delta and keep a last time variable. You could also count 20 loops and do it that way.

File: libraries/AP_Mount/AP_Mount_Scripting.cpp [hunk 14]
```diff
@@ -94,9 +90,28 @@ bool AP_Mount_Scripting::healthy() const
 // returns true if a target location is available and fills in target_loc argument
 bool AP_Mount_Scripting::get_location_target(Location &_target_loc)
```
Comment (IamPete1) [inline libraries/AP_Mount/AP_Mount_Scripting.cpp]: Could be be done at the generic backend level so it works for all backends?

File: libraries/AP_Scripting/examples/get-target-location-mount-backend.lua (hunk 12 above)
Comment (neo-0007) [reply libraries/AP_Scripting/examples/get-target-location-mount-backend.lua]: Updated , thanks !

File: libraries/AP_Mount/AP_Mount_Scripting.cpp (hunk 14 above)
Comment (neo-0007) [reply libraries/AP_Mount/AP_Mount_Scripting.cpp]: Yes this can be done by  moving the implementation to `AP_Mount_Backend` , I am working on it !

**Comment by neo-0007** [comment]
Current situation after the suggested edits :

The get_location_target() is moved up to the generic backend so now all the inheriting backends can use this method , also  some of the unnecessary state variables are removed as we can use the initialized() method to check validity of a Location object .

A example lua script was written and it is used by an new autotest that test mount target location in all 7 modes. Tests is passing indicating that scripting backend is working good ! but for other backends the get_location_target() method is not tested !

Thankyou @peterbarker  and @IamPete1 for the suggestions , If any more  work is required i am happy to make any changes !

File: libraries/AP_Mount/AP_Mount_Backend.cpp [hunk 15]
```diff
@@ -934,6 +932,36 @@ bool AP_Mount_Backend::get_angle_target(float& roll_deg, float& pitch_deg, float
     return false;
 }
 
+// return target location if available
+// returns true if a target location is available and fills in target_loc argument
+bool AP_Mount_Backend::get_location_target(Location &_target_loc)
```
Comment (IamPete1) [inline libraries/AP_Mount/AP_Mount_Backend.cpp:938]: Please add a `#if AP_SCRIPTING_ENABLED` round this and the same method in the front end. Hopefully that will endup saving a little flash on boards without scripting.

**Review by peterbarker — CHANGES_REQUESTED** [review]
@neo-0007 still missing the requested `#if`s

**Comment by neo-0007** [comment]
@peterbarker , Updated !

**Comment by peterbarker** [comment]
@IamPete1 's request to add the guards in has been done, so I'm marking this for MergeOnCIPass.

Unfortunately master is currently broken, so will need to be rebased once the fix goes in.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by neo-0007** [comment]
Thanks everyone for all the guidance with this,
I learned a lot working on this especially about lua bindings and how to write tests !
 
 Thanks again!
