### PR TITLE
AP_Param: fix unexpected truncation of AP_Float parameters in expressions

### LINKED ISSUE #29660: type infererence to int for AP_xxx types error
example PR:
https://github.com/ArduPilot/ardupilot/pull/29624

likely also affected:
 - get_minimum_board_voltage() and related fns or maybe get() makes it ok?

### PR DESCRIPTION
**Pull request by tpwrules**
Fixes #29660 for floats at least. An expression like `float v = true ? float_param : 0;` would cause `float_param` to be truncated to an integer to match the other type. Fix by only letting `AP_Float` be converted to a float. It is still possible to get truncation with integer parameter types, e.g. `int16_t v = true ? int16_param : (int8_t)0;` but I don't think it's a problem at this point.

There is a bunch of subtlety and some caveats, please see the commit contents and messages for details. The issue contains a list of areas of the code whose behavior will be changed by this, but problems are exclusive to the ternary operator and overloaded functions, not standard arithmetic operators.

Tested on Cube Orange that the `CAMERA_FOV_STATUS` message now does not truncate the FOV values specified in the corresponding parameters.

### CODE REVIEW

**Comment by peterbarker** [comment]
@Safe-bet more of the same issues were found, so thanks for bringing that float-truncation problem to our attention!

File: ArduCopter/Copter.cpp [hunk 1]
```diff
@@ -889,7 +889,7 @@ void Copter::update_super_simple_bearing(bool force_update)
     }
 
     super_simple_last_bearing = bearing;
-    const float angle_rad = radians((super_simple_last_bearing+18000)/100);
+    const float angle_rad = radians((float)((super_simple_last_bearing+18000)/100));
```
Comment (tridge) [inline ArduCopter/Copter.cpp:892]: should be 0.01

**Comment by Safe-bet** [comment]
> @Safe-bet more of the same issues were found, so thanks for bringing that float-truncation problem to our attention!

Thank you very much, @peterbarker. It feels good to be appreciated. It was my first PR, and I hope to contribute more in the future through Github and hopefully as a part of GSOC.

File: libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp [hunk 2]
```diff
@@ -475,8 +475,8 @@ void NavEKF3_core::FuseSideslip()
 void NavEKF3_core::FuseDragForces()
 {
     // drag model parameters
-    const ftype bcoef_x = frontend->_ballisticCoef_x;
-    const ftype bcoef_y = frontend->_ballisticCoef_y;
+    const ftype bcoef_x = frontend->_ballisticCoef_x.get();
+    const ftype bcoef_y = frontend->_ballisticCoef_y.get();
```
Comment (peterbarker) [inline libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp:479]: I wonder if these would be clearer as casts-to-ftype rather than .get()

similarly for many of the other casts.

Comment (rmackay9) [reply libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp:479]: I think ".get()" is prettier than a cast..

Comment (tpwrules) [reply libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp:479]: It would also have to be two casts, first to `float` then to the desired type, as we probably don't wish to implement cast operators for all desired types.

**Review by tridge — APPROVED** [review]
thanks for all your work on this!
I am curious why "return this->_value;" instead of "return _value;" ?

**Comment by tpwrules** [comment]
> I am curious why "return this->_value;" instead of "return _value;" ?

Some strange namespacing rule I did not fully comprehend and this was the simplest fix for. The latter does not compile.

**Review by peterbarker — APPROVED** [review]
