### PR TITLE
AP_GPS: Allow HIL_GPS to flag vertical velocity

### LINKED ISSUE #7997: Unable to set `EK3_GPS_TYPE = 0` when using mavlink HIL_GPS message
#### Issue details
I am using a mavlink HIL_GPS message to send (fake) GPS data to the Ardupilot. Attempting to set EK3_GPS_TYPE to 0 results in the error: EK3: Changed EK3_GPS_TYPE to 1. The HIL_GPS message is generated from an Optitrack motion capture system via the [mavros fake_gps plugin](https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/fake_gps.cpp), and does include accurate 3D velocity information. 

#### Version
3.6-dev

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad-X

#### Hardware type
pixhawk 2.1

### PR DESCRIPTION
**Pull request by WickedShell**
Closes #7997

### CODE REVIEW

File: libraries/AP_GPS/AP_GPS_MAV.cpp [hunk 1]
```diff
@@ -132,12 +132,15 @@ void AP_GPS_MAV::handle_msg(const mavlink_message_t *msg)
             }
             Vector3f vel(packet.vn/100.0f, packet.ve/100.0f, packet.vd/100.0f);
             state.velocity = vel;
+            if (packet.vd != 0) {
+                state.have_vertical_velocity = true;
```
Comment (OXINARF) [inline libraries/AP_GPS/AP_GPS_MAV.cpp]: We might need to document this type of stuff, some drivers will never go back to false, others will. I guess it depends on whether we know if vertical velocity is lost or not; here we couldn't know if velocity is back to really being 0 or if it's lost so I think this is the best approach.

**Comment by OXINARF** [comment]
Merged, thanks!
