### PR TITLE
AP_Proximity/AP_Airspeed: corrected return type of uart::read()

### LINKED ISSUE #21836: AP_Proximity/AP_Airspeed: uart::read() returns int16_t
A number of drivers are using the incorrect return type when calling uart::read()

- AP_AirSpeed_NMEA (uses char)
- AP_Proximity_Cygbot_D1 (uses uint8_t)
- AP_Proximity_RPLidarA2 (uses uint8_t)
- AP_Proximity_TeraRangerTower (uses char)
- AP_Proximity_TeraRangerTowerEvo (uses char)

### PR DESCRIPTION
**Pull request by prathamesh7255**
Fixes #21836.
The actual return type is int16_t.
Thank you.

### CODE REVIEW

**Comment by prathamesh7255** [comment]
I have a doubt, though. I have replaced the return type, but when it was assigned to char earlier, it compared the output of read() with 'T' further in the code. Now that I have assigned it to int16_t, what should I replace 'T' with?

**Comment by IamPete1** [comment]
Need to check for the -1 return for failed now its possible. After the check you can just cast to char as before.

**Comment by prathamesh7255** [comment]
> Need to check for the -1 return for failed now its possible. After the check you can just cast to char as before.

@IamPete1 sir okay, I will do it. How should I handle the -1 case? should it return or break the loop or anything else?

**Comment by prathamesh7255** [comment]
@IamPete1 sir, please look to see if its fine now.
Thank you.

File: libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp [hunk 1]
```diff
@@ -62,8 +62,11 @@ bool AP_Proximity_TeraRangerTower::read_sensor_data()
     int16_t nbytes = _uart->available();
 
     while (nbytes-- > 0) {
-        char c = _uart->read();
-        if (c == 'T' ) {
+        int16_t c = _uart->read();
+        if (c==-1) {
+            return false;
+        }
+        else if (static_cast<char>(c) == 'T' ) {
```
Comment (rmackay9) [inline libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp:69]: I think this else can be removed because of the return before it.  Same for the TeraRangerTowerEvo.cpp changes as well. txs

**Comment by prathamesh7255** [comment]
@rmackay9 sir, I have made these changes now.
Thanks

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Merged, thanks!
